### ISSUE TITLE
httputil.CertFingerprints is unused

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1000]
```
$ git grep CertFingerprints
pkg/httputil/certs.go:// CertFingerprints returns a map of hash prefixes of the x509 certificate encoded in
pkg/httputil/certs.go:func CertFingerprints(certPEM []byte) (map[string]string, error) {
```

Looks like it's no longer used.
 
Delete?

**Comment by mpl** [comment]
ACK. I'd just like to do a bit of git archeology before, so i can remember what was using it.

**Comment by mpl** [comment]
Ok, the launcher was its only user, and we got rid of it when we switched to Let's Encrypt in 8813375592c735a80ba7c23b4f01881934c82d4c.
I'll remove.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/13466
