### ISSUE TITLE
Permanodes creation and setting Attributes to Permanodes via the HTTP API 

### ISSUE THREAD

**Issue by gdeverlant** [perkeep/perkeep#1007]
I was wondering if there is a way to pass commands to the other CMD binaries via the HTTP API for example to create a Permanode?

**Comment by bradfitz** [comment]
The Perkeep server doesn't have access to the cmd binaries, so there's no way to "pass commands" to them, but there is a way to create permanodes.

You just create an unsigned permanode, like:

```
{"camliVersion": 1,
  "camliSigner": "sha1-YOURIDENTITY",
  "camliType": "permanode",
  "claimDate": "2018-01-03T03:27:26.542174396Z",
  "random": "XdnQ8Kxnjcw5Nkv5kepv+iH5qfw="
}
```

And then pass that to the JSON signing handler as the `json` parameter. The response is the signed JSON, which you can upload.

See these docs, just pushed:

https://perkeep.org/doc/protocol/jsonsign

**Comment by gdeverlant** [comment]
Although your link to documentation I don't get it because there is no example. The explanation is to foggy.

I'm sorry :(

**Comment by bradfitz** [comment]
Which part is unclear? A permanode is just a signed JSON blob where the JSON blob (prior to signing) is like the example above, with the random string of characters, date, and `camliSigner` value set to your identity. (the sha1-YOURIDENTITY) is the blobref to your public key PEM file, but it's the same value as you get from the discovery call (https://perkeep.org/doc/protocol/discovery and its **publicKeyBlobRef**)

So to make a permanode, you make that unsigned JSON, then POST it to the signing handler as the `json` POST parameter and you get it back signed. And that's a permanode.

**Comment by gdeverlant** [comment]
Although your link to documentation I don't get it because there is no example. The explanation is too foggy.

Here is what I want to do:

1. I created a little program that watch a **specific folder**.
2. **Every time** that a **new file** comes to that folder the **watcher** reacts.
3. The **watcher** generates the sha1 hash of the ByteArray from the file.
4. The **watcher** fetches the modifiedDate from the file.
5. The **watcher** creates a Hash class instance with the following params: 
```(hash:String, modifiedDate:Number, data:ByteArray, file:File)```
6. The **watcher** check in the **dictionnary[file.filename + file.extension]** if its **Hash** object exists.
7. If the **Hash** object does not exists:
7.1The **watcher** adds to the **dictionnary[file.filename + file.extension]** the non-existent previously generated **Hash** object.
7.2 The **watcher** adds the **Hash** object into the **filesToProcess** array.
8. If the **Hash** object does exist:
8.1 The **watcher** compare the existing **Hash** object with the new **Hash** object.
8.2 The comparison is made into the **isNewer** function:
`function isNewer(oldHash:Hash, newHash:Hash):Boolean{`
`return (newHash.hash != oldHash.hash && newHash.modifiedDate > oldHash.modifiedDate);`
`}`
8.3 If the new **Hash** object is different from the old one, the **watcher** replaces the old **Hash** object at **dictionnary[file.filename + file.extension]** with the new one.
8.4 The **watcher** adds the **Hash** object into the **filesToProcess** array.
9. When all the verification from the files is done, the **watcher** send an event with the **filesToProcess** array.

How should I proceed here if I want to **send** the file to **Peerkeep** ?

**Comment by gdeverlant** [comment]
I think that this use case could be a real one documented inside of the documentation for better understanding.

What do you think?

**Comment by bradfitz** [comment]
Attributes are the same as creating permanodes: it's just signing a JSON claim blob.

**Comment by gdeverlant** [comment]
Do you have any suggestion for my use case ? https://github.com/camlistore/camlistore/issues/1007#issuecomment-354942481

**Comment by gdeverlant** [comment]
I get it now after reading the documentation many times It starts to take form in my mind.
I found a library which allows me to upload multi-part requests. Now i will try my first request.

I would need only your help for https://github.com/camlistore/camlistore/issues/1007#issuecomment-354942481 because I don't know the exact order what to do.

Do I need to upload the file first?
After file uploaded do I create a permanode?
Set the permanode camliContent attribute to the sh1 of the uploaded file?

Thanx for your feedback!

**Comment by gdeverlant** [comment]
This is my first result that I get:

Request without header:
```
--cuyqwbhrfydpirshixhucejdptiuqfmv

Content-Disposition: form-data; name="sha1-da39a3ee5e6b4b0d3255bfef95601890afd80709"; filename="EmbbederBundle.swf"

Content-Type: application/octet-stream

CWS҂xì½|[Ùy'zÏ-8èØ%R¢
%A°ª+$rÔFT¸$G$È!Hq£Ç3qÜbÇqcË:ÅÙMâxS7ñÄyÙMb'5qIۗòÒ^²Op痗Ý}³ÿïÜ{A J3ßküñ܋{Êwzûê-IýsIò~Qj4V^'IÒ;*¿Î$éèj\<?i¾µ´L
âë؁񵵕ÁÎΛ7ovÜìîX^ëìè:C¡vÄhOÝN®Ånµ'S{Æ©ÙՅµåd3Í,¯¯;pÀÍ]Y_] 㳝ÅÄR"¹êìêè ø젾
...........................................
...........................................
...........................................
continuing file bytes

--cuyqwbhrfydpirshixhucejdptiuqfmv--
```

Call result:
```
completeHandler: {
  "received": [],
  "errorText": "Error reading multipart section: malformed MIME header line: CWS\u000e҂\u0001\u0000x\u0001\ufffd\ufffd\u0007|[\ufffdy'z\ufffd-8\ufffd\u0004\u001b\ufffd%R\ufffd"
}
```

**Comment by bradfitz** [comment]
Looks malformed for multiple reasons, some of which are are probably due to copy/paste. But there needs to be a double CRLF ("\r\n\r\n") after the Content-Type line there before the body begins. Are you doing your own multipart/mime or using a library?

**Comment by gdeverlant** [comment]
I'm building the part manually... I fixed the CRLF:

```
completeHandler: {
  "received": [],
  "errorText": "Error receiving blob sha1-da39a3ee5e6b4b0d3255bfef95601890afd80709: corrupt blob; digest doesn't match\n"
}
```

**Comment by gdeverlant** [comment]
Should I use the SHA256 algorithm for the hash instead?

**Comment by bradfitz** [comment]
No, only sha1 is supported at the moment. (We need to fix that soon.)

But sha1 should work. Maybe you have extra whitespace at the end.

**Comment by gdeverlant** [comment]
It works !!!!!!! HOURRAAYYY

```
completeHandler: {
  "received": [
    {
      "blobRef": "sha1-0568f40b12f13c31331838ed7b0f0ae929d17c01",
      "size": 39525
    }
  ]
}
```

**Comment by gdeverlant** [comment]
It seems that the file upload doesn't create a **Permanode** + a **Mutation** claims** which set the **camliContent** attribute to the **blobRef** of the uploaded file.

Do I need to do that manually everytime?

**Comment by mpl** [comment]
yes, you need to do all 3 if you want the file to be anchored by a permanode.

Yes, the UI does it as well the same way. Either directly in javascript (xmlhttprequest), or indirectly with GopherJS.

**Comment by gdeverlant** [comment]
Is it possible to create **Mutation claims** via the HTTP API? I've checked the documentation and cannot find any API endpoint for that.

**Comment by bradfitz** [comment]
A mutation claim is just another signed JSON blob. Make the unsigned JSON claim, sign it, and upload it.

**Comment by gdeverlant** [comment]
I was able to make the **Permanode** and sign it. Now I want to know if it is possible to upload a blob with the **application/x-www-form-urlencoded**  upload?

**Comment by gdeverlant** [comment]
I've analyzed the HTTP Requests from Chrome coming from the UI and here are my findings:

1. The UI sends the file to this url : **http://localhost:3179/ui/?camli.mode=uploadhelper**.
2. The response is totally different from what I get when I use the **POST to $BLOB_ROOT/camli/upload** url.
```
UI response
{
  "got": [
    {
      "filename": "FragmentsBundle.swf",
      "modtime": "2017-12-31T16:37:19Z",
      "formname": "ui-upload-file-helper-form",
      "fileref": "sha1-9d9cfb8b6d6bc59f86afd1c6967825a3e3bf3e10"
    }
  ]
}

My response
onUploadComplete: {
  "received": [
    {
      "blobRef": "sha1-0568f40b12f13c31331838ed7b0f0ae929d17c01",
      "size": 39525
    }
  ]
}
```

**Comment by gdeverlant** [comment]
Sending the file to the UI address works finally because I added the modtime param to the request.
