### ISSUE TITLE
Repeated error triggered in console indefinitely

### ISSUE THREAD

**Issue by gdeverlant** [perkeep/perkeep#1012]
This happens in the phase **5**

HTTP API

1. Upload file
2. Sign Permanode
3. Upload Permanode
4. Sign Claim
5. **Upload Claim**

![image](https://user-images.githubusercontent.com/26530975/34579611-f748f326-f189-11e7-9ff6-a0423b67f1a7.png)

**Comment by bradfitz** [comment]
Seems like your JSON-signed blobs aren't formatted right yet.

See https://perkeep.org/doc/json-signing/#signing

Can you include one of the failing blobs here so we can see what's wrong with it?

**Comment by gdeverlant** [comment]
I just tried to parse the signed Blob on this web site and the SHA1 hash is totally different.

String to hash:
```
{"camliSigner":"sha1-d7d83f315043309c6e428bd3af09762c56e37713","camliType":"permanode","claimDate":"2018-01-06T09:08:59Z","random":"K08VAAx37gjzY2dLQ6w8TBz12sFbKfk8","camliVersion":1,"camliSig":"wsBcBAABCAAQBQKIbgkACRCzBj716J2SYQAAsLMIABVp5HkGMsVh761+JNzZUnBEdHZKlo0S6kokVa53LclE4Pu2bSY4iUj6s1Dwv0CwUEKuJcTy6W4Fyb7hpC14D4O78BS4gy3EbomUQ0vt0/GpW93fbSTOz2NMAzdOWk7y4F3k33WHS6PGDNr3AplfgxbCMyVQMm/Bl+t4e/FTf7t1M1mYn8lU+wOlygB1RloSWXYy7gvQD3ksotfOcpZC72qeWrIk5zQMx+gMEHylgiXqSyTc1LtqMhT7kXz/A+yxO2qR2IP5KJVtj7xyOi7PxdkdDQBlFs52Jd3v8otEoI6HQGDQTX32n59NHNmY2fHiM8lFKSf5zWxOHfgadl1nkaQ==emgX"}
```
Result for sha1:  21004f306bef143175f4bd66a470a9029034ad40

![image](https://user-images.githubusercontent.com/26530975/34643610-75274146-f327-11e7-927e-e2ac51206cad.png)

**Comment by gdeverlant** [comment]
I will close this because it all works!
