### ISSUE TITLE
How to verify if a filename exist and upload a new version of this file with versioning

### ISSUE THREAD

**Issue by gdeverlant** [perkeep/perkeep#1021]
Hi again AGAIN :D!

I would like to know how is it possible in Perkeep to check before for the existence of a file.

The following process is working in my development environment and it is the only one I've implemented at the moment but it is rather limited. **Note** the process is the same as when one Drag&Drop a file on the UI, except that it is done via the HTTP API :

1. Uploading a binary file
2. Creating a dummy Permanode
3. Signing the dummy Permanode
4. Uploading the signed Permanode
5. Creating a dummy Claim (claimType:"set-attribute", claimAttribute:"camliContent") which points to **1**
6. Signing the dummy Claim
7. Uploading the signed Claim

I would like to upload the revision version of the existing file on Perkeep with the revisioning mechanism. I just don't know or understand how to model the operation.

Thank you again

**Comment by mpl** [comment]
This kind of thing is done in pkg/client/upload.go , in particular see func (c *Client) fileMapFromDuplicate(fileMap *schema.Builder, wholeRef blob.Ref)

In terms of an external client like you, I think what you want to do is:
1) compute the wholeRef of your file contents
2) issue a request to the search handler to see if there is any existing fileRef for this wholeRef
3) if one is found, stat the blobserver to see if it already has this fileRef blob. But probably overkill; if the search/index found it, it means it was already uploaded to the blobserver.

**Comment by gdeverlant** [comment]
Is there any HTTP API endpoint which can facilitate this?

**Comment by mpl** [comment]
the specific /files endpoint takes a "wholedigest" query parameter (see https://perkeep.org/pkg/search/handler.go?#L648), so i think you want something like:

http://localhost:3179/my-search/camli/search/files?wholedigest=sha1-digestofyourfilecontents

which should return all the file schemas (different versions in time) for this file contents

alternatively, you can POST a query to the search handler where you can look for pretty much anything you want, as per https://perkeep.org/pkg/search/#SearchQuery

**Comment by gdeverlant** [comment]
Ok I create 2 API Call and it works!
