### ISSUE TITLE
sorted/postgres: panic from fresh setup

### ISSUE THREAD

**Issue by adamdecaf** [perkeep/perkeep#1022]
I was looking to fix https://github.com/perkeep/perkeep/issues/258, but can't get postgres up and running. Here's the steps:

Start postgres: `docker run -p 5432:5432 -it postgres:latest`

`camtool dbinit -dbtype postgres -sslmode disable -user postgres -dbname perkeep -wipe`
(no output, but success)

Setup config:

```
$ cat ~/.config/camlistore/server-config.json 
{
    "auth": "localhost",
    "listen": ":3179",
    "camliNetIP": "",
    "identity": "3A94488D",
    "identitySecretRing": "/Users/adam/.config/camlistore/identity-secring.gpg",
    "blobPath": "/Users/adam/Library/Camlistore/blobs",
    "packRelated": true,
    "postgres": "postgres@127.0.0.1:",
    "dbname": "perkeep"
}
```

Launch `camlistored`:

```
$ ./bin/camlistored 
2018/01/07 13:35:41 Starting camlistored version 2018-01-07-7a54a2c07a+; Go go1.9.2 (darwin/amd64)
2018/01/07 13:35:41 Starting to listen on http://localhost:3179
2018/01/07 13:35:41 Caught panic installer handlers: error instantiating storage for prefix "/bs/", type "blobpacked": failed to setup blobpacked metaIndex: error from "postgres" KeyValue: error creating table with "CREATE TABLE IF NOT EXISTS rows (\n k VARCHAR(767) NOT NULL PRIMARY KEY,\n v VARCHAR(63000))": pq: database "pk_3a94488d_blobpacked" does not exist
goroutine 1 [running]:
runtime/debug.Stack(0xc420088140, 0x2, 0xc420daa000)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc420445c68)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:540 +0xa8
panic(0x1b46420, 0xc4201e66f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420d4d980, 0xc4209d8e00, 0x1d78417, 0xb)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0x1b46420, 0xc4201e66f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420d4dbc0, 0xc4209d8e00, 0x1d739e0, 0x7)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0x1b46420, 0xc4201e66f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc420d4d7d0, 0xc4209d8e00, 0x1d70b64, 0x4)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0x1b46420, 0xc4201e66f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.exitFailure(0x1da77bc, 0x36, 0xc4204449e0, 0x3, 0x3)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:277 +0x16e
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc4209d8e00, 0x1d70b64, 0x4)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:323 +0x3a7
perkeep.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc4209d8e00, 0x1d70b64, 0x4, 0x0, 0x0, 0xe26dee700e14cdd5, 0x5b32478790c7a4c5)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:251 +0x43
perkeep.org/pkg/index.newFromConfig(0x28fac60, 0xc4209d8e00, 0xc420d4d3b0, 0x5, 0xc42048f910, 0x102bd01, 0xc420d52a30)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/index/index.go:308 +0x181
perkeep.org/pkg/blobserver.CreateStorage(0x1d7b120, 0x5, 0x28fac60, 0xc4209d8e00, 0xc420d4d3b0, 0x7, 0x1, 0x2, 0x1012907)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/blobserver/registry.go:111 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc4209d8e00, 0x1d739e0, 0x7)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:321 +0x25c
perkeep.org/pkg/serverinit.(*handlerLoader).GetHandler(0xc4209d8e00, 0x1d739e0, 0x7, 0x0, 0x1, 0x0, 0x0)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:259 +0x43
perkeep.org/pkg/search.newHandlerFromConfig(0x28fac60, 0xc4209d8e00, 0xc420d4d290, 0x6, 0xc420080570, 0x102bd01, 0xc420088440)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/search/handler.go:151 +0x189
perkeep.org/pkg/blobserver.CreateHandler(0x1d7355e, 0x6, 0x28fac60, 0xc4209d8e00, 0xc420d4d290, 0xb, 0x0, 0x1, 0x29f3a00)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/blobserver/registry.go:140 +0xc3
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc4209d8e00, 0x1d78417, 0xb)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:370 +0xa9e
perkeep.org/pkg/serverinit.(*handlerLoader).setupAll(0xc4209d8e00)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:231 +0x92
perkeep.org/pkg/serverinit.(*Config).InstallHandlers(0xc420d8a100, 0x28e8b00, 0xc420d23540, 0xc420d5d960, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/serverinit/serverinit.go:609 +0xb7e
main.Main(0x0, 0x0)
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/server/camlistored/camlistored.go:760 +0x4dd
main.main()
	/Users/adam/code/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/server/camlistored/camlistored.go:703 +0x33
Error parsing config: Caught panic: error instantiating storage for prefix "/bs/", type "blobpacked": failed to setup blobpacked metaIndex: error from "postgres" KeyValue: error creating table with "CREATE TABLE IF NOT EXISTS rows (\n k VARCHAR(767) NOT NULL PRIMARY KEY,\n v VARCHAR(63000))": pq: database "pk_3a94488d_blobpacked" does not exist
```

Removing `dbname` from `server-config.json` still panics.  Setting `"dbUnique": ""` doesn't helper either.

I see that [dbname](https://github.com/perkeep/perkeep/commit/7eda9fd5027fda88166d6c03b6490cffbf2de5fb#diff-7a20eced8e573ca2dc6df9dac8bd530dR134) takes priority for the index db, but not the others? 

https://github.com/perkeep/perkeep/blob/7a54a2c07a88a30eb0d8df63c8544c1b2d9a97c4/pkg/serverinit/genconfig.go#L136-L148

**Comment by adamdecaf** [comment]
`"postgres": "postgres@127.0.0.1:",` was a bit weird. I needed a connection that didn't have a password.  

I had to edit `cfg.OptionalString("sslmode", "disable")`. Is `sslmode` an accepted setting? I couldn't get allowed in the config.

**Comment by adamdecaf** [comment]
Mysql looks to create databases -- so I assume postgres is just missing that?

https://github.com/perkeep/perkeep/blob/master/pkg/sorted/mysql/mysqlkv.go#L164

**Comment by bradfitz** [comment]
> I was looking to fix #258, but can't get postgres up and running.

Now there's 2 more things to fix! This, and fixing our CI to regularly run Postgres tests to catch regressions like this in the future.

>  pq: database "pk_3a94488d_blobpacked" does not exist

@mpl just changed database names.

Mathieu, do you ever test Postgres?

> I had to edit cfg.OptionalString("sslmode", "disable"). Is sslmode an accepted setting? I couldn't get allowed in the config.

Looks like it's valid from the code. What happened for you?

**Comment by adamdecaf** [comment]
```
$ ./bin/camlistored 
2018/01/07 14:16:14 Starting camlistored version 2018-01-07-7a54a2c07a; Go go1.9.2 (darwin/amd64)
Error loading config file: unknown high-level configuration parameter: "sslmode"
```

```
$ cat ~/.config/camlistore/server-config.json 
{
    "auth": "localhost",
    "listen": ":3179",
    "camliNetIP": "",
    "identity": "BFC54B6D",
    "identitySecretRing": "/Users/adam/.config/camlistore/identity-secring.gpg",
    "blobPath": "/Users/adam/Library/Camlistore/blobs",
    "packRelated": true,
    "postgres": "postgres@127.0.0.1:",
    "sslmode": "disable"
}
````

**Comment by bradfitz** [comment]
The key word in that error message is "high-level configuration". There are two configuration types: the high-level simple config, and the low-level nasty one.

"sslmode" (and what you see in the code) is for the low-level one.

Set the environment variable `CAMLI_DEBUG_CONFIG=true` or `CAMLI_DEBUG_CONFIG=1` when you run camlistored to see the resulting low-level config from the high-level config.

To add support for sslmode to the high-level config, see pkg/serverinit/genconfig.go.

But we'd probably want to pack that into the "postgres" connection string, rather than making a new free-floating "sslmode" that looks ambiguous.

**Comment by mpl** [comment]
No, aside from the specific GCE case that I checked more thoroughly to verify its particular fix worked, I only ran our unit tests, which i believe do not test that a Perkeep instance with postgres runs.
So yes, more integration tests in that vein would of course be better.

**Comment by adamdecaf** [comment]
It looks like the high to low level parsing for db connection string info keeps everything generic. We could parse out a "query" blob (similar to a URL's query) and pass that down? I don't think we'd want to readout "sslmode" here somehow. 

https://github.com/perkeep/perkeep/blob/7eda9fd5027fda88166d6c03b6490cffbf2de5fb/pkg/serverinit/genconfig.go#L404-L410

**Comment by adamdecaf** [comment]
BTW, is `user@host:password` intentional? URL authorities are `user:host@password`.

**Comment by bradfitz** [comment]
> BTW, is user@host:password intentional? URL authorities are user:host@password.

Don't you mean `user:password@host`?

I have no memory of that being intentional. @mpl?

Changing it now would break people, though.

**Comment by bradfitz** [comment]
We can break people, though, as long as we keep the GCE launcher working for people who can't tweak their configs.

**Comment by adamdecaf** [comment]
https://github.com/perkeep/perkeep/blob/master/pkg/serverinit/genconfig.go#L395

Yea, `user:password@host` would make more sense to me.

**Comment by mpl** [comment]
I think we historically did it that way because one of the underlying DBMS (I don't recall which one) uses this kind of syntax, and why not pick the same syntax in the high-level config.

I don't really see the gain for changing that syntax here. It is already well documented, it won't make the code any simpler, and it will break users.

**Comment by adamdecaf** [comment]
Keep `user@host:password`? We'll need to update some of the docs. I can grab that.

**Comment by adamdecaf** [comment]
I've got a patch that creates databases on startup now, but I'm running into what I think is a big with `lib/pq`.

Also, there seems to be another bug where on restart uploaded files don't re-appear and `camtool index` seems to hang. Once I get the db creation sorted out it'll be a bit easier to track down `camtool index`.

```
$ camtool -verbose index
2018/01/07 19:39:38 At source blob sha1-03b883106c1b5d5a17d59258f4220bee49bb223d (1 blobs, 549 bytes)
```

**Comment by mpl** [comment]
@adamdecaf Are you looking into this panic, or do you want me to do it?

If the latter, can you please tell me if the panic is indeed postgres specific, or if we're just forgetting to create a DB whatever the DBMS is (i.e. with MySQL too)?

**Comment by adamdecaf** [comment]
@mpl I'm looking at the panic. I've got most of a patch ready that fixes that. I can push that if y'all want. 

The panic seems to be postgres specific. Missing `create database $name` calls.

**Comment by adamdecaf** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/13106 

I'm not too happy with it because of that regex around database names, but camlistored doesn't panic now.
