### ISSUE TITLE
vendor/embed: Move embed files out of vendor

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1024]
With the conversion to dep in #889 we will need to move the vendor/embed directory some other place.  

dep and other vendoring systems require full control over the directory.

Interested in people's thoughts on solutions for embedding.

**Comment by bradfitz** [comment]
It used to be under `third_party`, before we renamed that to `vendor`. We could move it back.

Or pick some other name.

It all looks like frontend stuff:

* leaflet JS
* opensans font
* react JS
* glitch images
* closure JS
* fontawesome fonts
* less JS

So maybe the top-level directory 'frontend'?

Then we could have `frontend/embed` or `frontend/vendor` for those 7 bulleted things.

Maybe we could also move the frontend code from `server/camlistored/ui` to under `$ROOT/frontend` somewhere?

/cc @mpl

**Comment by bradfitz** [comment]
It's true that a web UI is a client, but I'm not sure everybody would intuitively classify it as such.

But `clients/web` for all frontend code and `clients/web/embed` for embedded stuff, or `clients/web/third_party` SGTM. @lindner, preferences?

**Comment by lindner** [comment]
Using clients/* consistently feels right to me.

It also would allow for breaking up clients into their own repos at some future point where they can follow the standards of their respective platforms.

**Comment by bradfitz** [comment]
@lindner, why don't you move it all to `clients/web/embed` or `clients/web/vendor` for now then. We can move the rest of the web code later in a separate change.
