### ISSUE TITLE
Integration test failure for non-utf8_test.go on macos 10.13.2

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1025]
This test started failing when I upgraded to High Sierra (aka 10.13.2)

Passes correctly on a linux host.

--- FAIL: TestNonUTF8FileName (0.00s)
	non-utf8_test.go:60: os.Create(): open /var/folders/xt/s0f6yl1x37b_2h5j2vsl60r8003nwk/T/camtest-943586621/Aliz�e - Moi Lolita.mp3: illegal byte sequence
--- FAIL: TestNonUTF8SymlinkTarget (0.00s)
	non-utf8_test.go:94: os.Create(): open /var/folders/xt/s0f6yl1x37b_2h5j2vsl60r8003nwk/T/camtest-238717304/Aliz�e - Moi Lolita.mp3: illegal byte sequence
FAIL
FAIL	perkeep.org/pkg/test/integration	26.040s

**Comment by bradfitz** [comment]
I can reproduce.

I'm actually kinda happy about this: finally a filesystem with the courage to be strict about encoding, even if POSIX says it's an arbitrary-ish sequence of bytes.

**Comment by bradfitz** [comment]
Specifically, syscall.Errno 0x5c,

2018/01/08 06:41:55 Got a &os.PathError{Op:"open", Path:"/var/folders/9l/46n0b92j78n_zn7pq7r1xq800000gn/T/camtest-678761069/Aliz\xe9e - Moi Lolita.mp3", Err:0x5c}

**Comment by lindner** [comment]
I also remember that Mac relies on using NFD for their unicode:

https://developer.apple.com/library/content/qa/qa1173/_index.html

I used mount NFS from linux<->mac and it always had these odd issues with my iTunes library...
