### ISSUE TITLE
devcam server panics because sourceRoot not found

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1032]
2018/01/10 19:58:21 Caught panic installer handlers: error instantiating handler for prefix "/ui/", type "ui": Invalid "sourceRoot" value of "/home/mpl/src/perkeep.org": directory doesn't contain goog/base.js; wrong directory?"

Probably because of the vendor/embed move.

**Comment by lindner** [comment]
thanks for fixing this.  Not sure how this got missed in manual testing.  I wonder if I had leftover data in tmp/ ?

**Comment by mpl** [comment]
@lindner np. I bet you got tricked by CAMLI_DEV_CLOSURE_DIR (that you properly fixed), which on first impression looks like it might be the part responsible for devcam server (which it isn't, in the general case).
