### ISSUE TITLE
server/camlistored: keep track of the Let's Encrypt issue

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1033]
golang.org/x/crypto/acme/autocert is broken at the moment, because of https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996

This affects camlistored, as it relies on golang.org/x/crypto/acme/autocert to obtain an HTTPS certificate.

**Comment by mpl** [comment]
TODO: revert https://camlistore-review.googlesource.com/#/c/camlistore/+/13286 when the issue is resolved.

**Comment by mpl** [comment]
https://twitter.com/bradfitz/status/951909513593958400

**Comment by bradfitz** [comment]
Yeah, please go ahead and do that.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/13486

**Comment by mpl** [comment]
reopening until I've fixed the website and camnetdns as well.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/13526 took care of camweb. still need to do camnetdns.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/14286

**Comment by mpl** [comment]
camnetdns restarted with the http-01 Let's Encrypt challenge
