### ISSUE TITLE
cmd/camtool: add a flag for camtool search to output non JSON list

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1034]
I fairly often want to run another command (say a 'camput file') on all the blobs in the output of a given camtool search.

At the moment I have my own go program that parses the output of camtool search and does that, but I figure maybe we could have some sort of -exec option for camtool search that runs the given command for each blob of the output.

Quite trivial to do and I bet it would be useful for others as well.

**Comment by jhillyerd** [comment]
Is the goal to pass the blob ref as a argument to the execed command, or to actually fetch the content of the blob and send that via stdin to the command?

The former would have limited value:  You could accomplish the same w/ `camtool search | sed ... | xargs`

The latter could be useful with `camput blob -`

**Comment by jhillyerd** [comment]
Have part of exec to stdin in working, but it just prints out a bunch of permanodes.  That doesn't feel useful to me, would it make sense to have it implicitly dereference the permanote and grab the contents?  or is that too much magic?

**Comment by mpl** [comment]
> The former would have limited value: You could accomplish the same w/ camtool search | sed ... | xargs.

sure you could. there's many ways to do this. I'm just saying figuring this out does not have to be left as an exercise to the user if we can easily add an option that does it for them.

> I have part of exec to stdin in working, but it just prints out a bunch of permanodes. That doesn't feel useful to me, would it make sense to have it implicitly dereference the permanote and grab the contents? or is that too much magic?

If you "dereferenced" the permanodes, then you'd be working on blobs that are not the result of the requested search, whatever that search is. So no, I think we should only exec on the blobs that are the direct result of the search.

**Comment by jhillyerd** [comment]
It's *quite* likely that I have no idea how to search correctly, but when I run a normal camtool search for `format:jpeg` I get back:
```
{
  "blobs": [
    {
      "blob": "sha224-10f9514b72cd92cc6530d18f43761d5aa5f471225ce702279cc214a5"
    }
  ],
  "description": null,
  "LocationArea": null
}
```

In this scenario, the exec stdin option would send the following to the executee:
```
{"camliVersion":1,
        "camliType": "permanode",
        "random": "0.45761650433517875",
        "camliSigner": "sha224-ea0ba9068820cc128e993b20d0511de736f..."
,"camliSig":"wsBcBAABCAAQBQKIbgkACRApMaZ8JvWr2gAAFLkIAH0QCT..."}
```

Given that the permanode JSON does not contain any sort of ref, it feels like a dead end to me.  Am I searching wrong, or is the stdin idea not useful?

**Comment by mpl** [comment]
I'm not sure what the stdin idea means.
This issue is for adding a flag that would allow to execute a given command that would take as input the blobRefs returned by the search. So in your example, the user supplied command would receive "sha224-10f9514b72cd92cc6530d18f43761d5aa5f471225ce702279cc214a5" as argument.

**Comment by jhillyerd** [comment]
Implemented, exits immediately if command fails.  No attempt made to split or glob the -exec parameter, so the command must be work with just the one argument.

```
$ bin/camtool search -exec echo 'attr:camliNodeType:"twitter.com:tweet"'
sha1-7783813db062bbf8ac1fbdaf9481877bf9d1d329
sha1-547b44859e7fc3e484e295fae1a09ad88b5ac961
sha1-fc285cc4df0eda5232d1b5a2a878d7e290e5c1ab
sha1-f741e7f9c263117108deeafbed6b3b5feecba23e
sha1-11e9c68ec49206deda008aab547523be664d6c16

$ bin/camtool search -exec false 'attr:camliNodeType:"twitter.com:tweet"'
Error: false: exit status 1
```

https://camlistore-review.googlesource.com/c/camlistore/+/14466

Assuming I don't need to assign a reviewer manually?

**Comment by mpl** [comment]
> Assuming I don't need to assign a reviewer manually?

No that's fine. All relevant devs receive e-mails for the CLs.

**Comment by mpl** [comment]
> https://camlistore-review.googlesource.com/c/camlistore/+/14466

hmm this is debatable, but I'd rather have the command run only once, and it gets _all_ the search result blobrefs as arguments. I know this is not what find -exec does, but it's more efficient (and it fits my use case better). But I'm willing to be convinced otherwise. One argument I can think of, might be some limit to the number of arguments that a command can receive, even though I don't remember where this kind of limit is enforced.

WDYT?

**Comment by jhillyerd** [comment]
It looks like POSIX defines a minimum cap of 4096 characters, but most of the operating systems on [this (rather outdated) list](https://www.in-ulm.de/~mascheck/various/argmax/) handle more than 20,000.

Turns out that xargs can tell you your limits:
```
$ xargs --show-limits
Your environment variables take up 703 bytes
POSIX upper limit on argument length (this system): 2094401
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2093698
Size of command buffer we are actually using: 131072
Maximum parallelism (--max-procs must be no greater): 2147483647
```

Given that sha-224 blobrefs are 64 chars, Posix minimum allow for approx 60 args.  My machines "command buffer" would allow for about 2,000, but assuming that can grow to the maximum length listed above; about 32,000 max.

Not forgetting our [Windows friends](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string), it has a limit of 32767 chars: about 500 blobrefs.

The 60-2,000 blobrefs range feels rather low to me, a few years of tweets and retweets could overwhelm that.  We could chunk it?  Batches of N args, where N = 64..256?

**Comment by mpl** [comment]
ok, thanks for the research. I guess we can try batches indeed, but if you find out it gets too gnarly let's just stick with one command per blobRef for now.

**Comment by bradfitz** [comment]
I'd rather not adding things like `-exec` to camtool. It seems redundant with Unix tools that do this already. Can't you just pipe into `xargs -n 1`?

**Comment by mpl** [comment]
I can. But can all users?

**Comment by bradfitz** [comment]
How many users want `-exec`? And if we did have an `-exec`, it should work like `find`'s `-exec`. The proposed CL does not.

**Comment by mpl** [comment]
anyway, I've been in this situation often, but I have tools to deal with it myself now. If nobody else wants it, I don't need it either.
If anyone else wants it, feel free to reopen and make yourself known.

**Comment by jhillyerd** [comment]
I was never a fan of find's -exec, the `{} \;` thing confusing.  find | xargs is easier.

Current output of camtool search is JSON, so you can't throw it into xargs.  Which is why I suggested a `-list` parameter in my initial response.

**Comment by bradfitz** [comment]
Yes, we should have a non-JSON flag to print out simple lines of text, for easier interop with standard Unix tools.

**Comment by jhillyerd** [comment]
Thoughts on flag name?  `list`, `text`, `plaintext`, `nojson`.. ?

**Comment by jhillyerd** [comment]
or maybe `refs` or similar to make it clear what will be output?

**Comment by bradfitz** [comment]
We could name the flag `-1` like `ls`?

**Comment by jhillyerd** [comment]
I'll rework my -exec CL into this.

**Comment by jhillyerd** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14466
