### ISSUE TITLE
Google Launcher `docker load`s camlistore/* images, but tries to run perkeep/* images

### ISSUE THREAD

**Issue by colemickens** [perkeep/perkeep#1038]
I just booted a Google Cloud instance from: https://perkeep.org/launch/

Perkeep unit doesn't get to a running state properly: `camlistored` fails to start, due to the images not existing locally, and not actually being on Docker Hub:

On the instance:
```
cole_mickens@camlistore-server ~ $ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
camlistore/server           latest              f70566794781        4 months ago        28.3MB
camlistore/systemd-docker   latest              73c34a1f033f        2 years ago         9.98MB
camlistore/mysql            latest              5154d243f301        3 years ago         261MB
```

But I can see the unit in the GCE metadata trying to `docker run ... perkeep/server`.

Extra observation: The launcher page seems to make big deal out of saying which version it runs, but it appears to actually just import docker images from the latest docker tar.gz that was pushed as part of a release.

**Comment by mpl** [comment]
Can you please paste exactly what the logs say about camlistored not starting? (journalctl -u camlistored)

**Comment by mpl** [comment]
ah, the actual issue is in the title, I see what might be going on.

**Comment by mpl** [comment]
ok, new image is up, which should fix that issue. However, I suggest you wait a tiny bit longer, because we're about to fix the let's encrypt problem, and hopefully reupload a new image with that fix very soon.

**Comment by mpl** [comment]
@colemickens the new image with a fixed Let's Encrypt is now up. Could you please retry and let me know if it's working for you?
i think a 'systemctl restart camlistored' should be enough to get you working, but if in doubt deleting the instance and recreating from the launcher should be safer.

**Comment by colemickens** [comment]
@mpl Just kicked off an instance. The landing page, with key: https://perkeep.org/launch/instance?instancekey=sha224-7250c2683520d21f78fba3b989017b0d6b02ef768b16c37d79291339

Note, if you hit that IP, it redirects to https, but isn't actually serving SSL.

Let me know, I can open a new Issue for this, since the images seem to be resolved.

**Comment by mpl** [comment]
@colemickens I think I see what you mean (I can't check since the link now shows the "real success" page), but I'm not sure that's an issue. The IP displayed there is more like an FYI, since your instance is given an actual FQDN (that you get when you refresh the page, as the text says) to make it fully functional over HTTPS. In any case, I'll recheck the code to see what our intent was here.

Yes, please leave this issue open until I can give you a more complete answer (and/or a fix).

**Comment by colemickens** [comment]
@mpl Gotcha. It looks like maybe camlistored came up before the LE challenge was finished?

(Note, the error I got wasn't "bad cert" or anything, it was that I was hitting an https:// endpoint that wasn't actually serving TLS.)

Anyway, looks like it settled correctly. I might have expected it to not come up until the cert was available, or serve with a self-signed cert until the LE cert was in place, etc. Not a big deal to me, though.

**Comment by mpl** [comment]
Yeah I've just rechecked, and this IP address is not meant to show up as a link (and it does not afaict), so I think it's fair to expect the user to treat it just as an FYI (and not as a viable link), right?

**Comment by colemickens** [comment]
Yeah, as far as I'm concerned here, there's no issue.

To be honest though, I didn't know the contents of the landing page were going to change after the LE process finished. That would be my only nit, is the temporary landing page could be more clear (it's also possible it was, and I just missed it).

As far as I can tell, things are working fine and the UX is reasonable, yes. As such, I'm going to go ahead and close this. Thanks for the support and fast turn around, @mpl.
