### ISSUE TITLE
pkg/client and pkg/serverinit tests fail

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1040]
2018/01/22 20:32:57 Caught panic installer handlers: error instantiating handler for prefix "/ui/", type "ui": Invalid "sourceRoot" value of "/home/mpl/src/camlistore.org": directory doesn't contain goog/base.js; wrong directory?"
goroutine 25 [running]:
runtime/debug.Stack(0xc420080190, 0x2, 0xc4202980e0)
	/home/mpl/go1.9/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/home/mpl/go1.9/src/runtime/debug/stack.go:16 +0x22
perkeep.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc42017ba68)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:541 +0xa8
panic(0xae4760, 0xc420010f80)
	/home/mpl/go1.9/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4202335c0, 0xc4201e6d00, 0xc00684, 0x4)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:309 +0x1a2
panic(0xae4760, 0xc420010f80)
	/home/mpl/go1.9/src/runtime/panic.go:491 +0x283
perkeep.org/pkg/serverinit.exitFailure(0xc2a45b, 0x36, 0xc42017b470, 0x3, 0x3)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:278 +0x16e
perkeep.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc4201e6d00, 0xc00684, 0x4)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:373 +0xbc9
perkeep.org/pkg/serverinit.(*handlerLoader).setupAll(0xc4201e6d00)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:232 +0x92
perkeep.org/pkg/serverinit.(*Config).InstallHandlers(0xc4201c72c0, 0xff92e0, 0xc420233500, 0xc4202c6710, 0xc, 0xc4202c6700, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mpl/src/perkeep.org/pkg/serverinit/serverinit.go:610 +0xb7e
perkeep.org/pkg/client.newTestServer(0xc4202b4690, 0x0)
	/home/mpl/src/perkeep.org/pkg/client/upload_test.go:152 +0x522
perkeep.org/pkg/client.TestUploadFile(0xc4202b4690)
	/home/mpl/src/perkeep.org/pkg/client/upload_test.go:71 +0x52
testing.tRunner(0xc4202b4690, 0xc80758)
	/home/mpl/go1.9/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/mpl/go1.9/src/testing/testing.go:789 +0x2de
--- FAIL: TestUploadFile (0.00s)
	upload_test.go:154: Caught panic: error instantiating handler for prefix "/ui/", type "ui": Invalid "sourceRoot" value of "/home/mpl/src/camlistore.org": directory doesn't contain goog/base.js; wrong directory?"

probably trivial to fix but busy with something else rn.

**Comment by lindner** [comment]
camlistore.org vs perkeep.org?

**Comment by mpl** [comment]
yeah. dunno how that flew below the radar.
https://camlistore-review.googlesource.com/#/c/camlistore/+/13706
