### ISSUE TITLE
pkg/client: panic because httpGate is undefined

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1043]
when running devcam server:

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e0058]
	
	goroutine 1 [running]:
	perkeep.org/vendor/go4.org/syncutil.(*Gate).Start(...)
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/vendor/go4.org/syncutil/gate.go:31
	perkeep.org/pkg/client.(*Client).doReqGated(0xc4201f5900, 0xc4201d8400, 0x0, 0x0, 0x0)
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/client/client.go:1182 +0x48
	perkeep.org/pkg/client.(*Client).expect2XX(0xc4201f5900, 0xc4201d8400, 0xc420094038, 0xb14de4, 0x3)
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/client/client.go:1171 +0x4d
	perkeep.org/pkg/client.(*Client).GetJSON(0xc4201f5900, 0xe9d9c0, 0xc420094038, 0xc42001e3d5, 0x28, 0x9feae0, 0xc4202061c0, 0xc420000180, 0xb88330)
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/client/client.go:1098 +0xe2
	main.appConfig(0xc4200186f1, 0xf, 0x0)
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/app/publisher/main.go:106 +0x231
	main.main()
		/home/mpl/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/app/publisher/main.go:284 +0x3d2

that happens because app.Client used to call client.NewFromParams, which in turn was doing

       if c.httpClient == nil {
               c.httpClient = &http.Client{
                       Transport: c.transportForConfig(c.transportConfig),
               }
       }
       c.httpGate = syncutil.NewGate(httpGateSize(c.httpClient.Transport))

and that is not done anymore by client.Client when noExtConfig is set.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/13806

**Comment by bradfitz** [comment]
@mpl, this bug still being open suggests that Gerrit to GitHub syncing is wedged. And indeed, it is.

**Comment by mpl** [comment]
yeah, as usual docker was stuck, so the git pull in container could not happen.
I've restarted docker.
