### ISSUE TITLE
camlistore/go repository doesn't seem to exist 

### ISSUE THREAD

**Issue by sergi** [perkeep/perkeep#1044]
Getting an error when doing `docker build .`.

```
$ docker build .
Sending build context to Docker daemon  65.92MB
Step 1/32 : FROM camlistore/go
pull access denied for camlistore/go, repository does not exist or may require 'docker login'
```

Am I missing something?

**Comment by bradfitz** [comment]
@sergi, we're still in the middle of the rename (#981).

Want to send a fix?

Or @mpl can do it.

**Comment by sergi** [comment]
I guess that would involve publishing `perkeep/go` docker repo to the Docker Hub, since I see there is a `camlistore/*` repo which is probably the one you were using in the past. In any case, you guys should own https://hub.docker.com/u/perkeep/, no?

**Comment by bradfitz** [comment]
Yes, we should own that. I'll let @mpl create it.

**Comment by mpl** [comment]
Actually this has nothing to do with hosting, as we never hosted the camlistore/go image anywhere either.
As the comment in the Dockerfile says, you're supposed to build the {camlistore/perkeep}/go image yourself with misc/docker/go.

Image name fixed here:
https://camlistore-review.googlesource.com/#/c/camlistore/+/14026
