### ISSUE TITLE
pkg/index: searches on sha1 blobs fail until at least one sha224 claim is in

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1047]
repro:

devcam server -publish false -scancab false -sha1 true -wipe true
CAMLI_SHA1_ENABLED=true devcam put file -filenodes foo
-> permanode sha1-foo is created
kill server, and restart:
devcam server -publish false -scancab false
devcam tool describe sha1-foo
-> no camliContent description
devcam put file -filenodes bar
devcam tool describe sha1-foo
-> description ok.

explanation: this happens, because the search API uses the signer blobRef (and not the signer KeyID), so from the API pov the same signer can be a sha1 blobRef or a sha224 one. We fixed most of the bugs related to that in pkg/index by working with a keyID instead of a signer blobRef, and by establishing a correspondence between the two blobRefs through the keyID.
However, this correspondence only exists as soon as the relation between the sha224 signer and the keyID is inserted in the index/corpus, which happens when we get our first signerid row for a sha224 blob, i.e. when we get our first sha224 claim. This the reason why camtool describe fails before we add the second file.

**Comment by bradfitz** [comment]
(Part of #537)

**Comment by mpl** [comment]
This issue is somewhat related to the fact that the search Handler is for now tied to an owner, because we actually initialize it with a fixed given owner. And that we use that owner as the signer for all search/describe requests I think.

We actually have a TODO about that in pkg/search/handler.go:

    // Owner returns Handler owner's public key blobref.
    func (h *Handler) Owner() blob.Ref {
    	// TODO: figure out a plan for an owner having multiple active public keys, or public
    	// key rotation
    	return h.owner
    }

So until we have a plan for the above TODO, I think it would be fair, since that owner is a requirement anyway, to manually insert the signeridkey row for that owner right after the corpus is populated. Which is incidentally, and conveniently, done in newHandlerFromConfig of the search handler. 

WDYT?

**Comment by bradfitz** [comment]
I don't want to require a server to do a write on start-up. (Related: remember when I added the devcam -mini option for demos? To show starting off with a blank slate?)

I think now's a good time to change that signature away from "blob.Ref".

We could make an "Owner" type somewhere with a set of blob.Refs that are known to be it, and/or a set of GPG IDs.

But if we make it a struct pointer, we can hide all the fields and grow the representation over time as needed, and just keep some methods on it.

**Comment by tajtiattila** [comment]
I would also like to see the signerFilter blob.Ref replaced with a signerID string (or []string for multiple owners, or users with multiple keys) in corpus API funcs. It would have made my work on my CL https://camlistore-review.googlesource.com/c/camlistore/+/12486 easier.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/14006

**Comment by lindner** [comment]
This change (verified with git bisect) seems to have broken my laptop install.  camlistored dies on startup with the following error message:

```
panic: Search result returned non-importerAccount

goroutine 41952 [running]:
perkeep.org/pkg/importer.(*Host).startPeriodicImporters(0xc42388d200)
	/Users/plindner/go/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/importer/importer.go:646 +0x574
created by perkeep.org/pkg/importer.(*Host).InitHandler
	/Users/plindner/go/src/perkeep.org/tmp/build-gopath-nosqlite/src/perkeep.org/pkg/importer/importer.go:478 +0x33b
```
I added some logging and the desBlob in importer looks like this:

```
desBlob=&{0xc425786000 sha1-29b33efba5b85161b41724b1305994f809666ec9 permanode 611 0xc420d4eb00 <nil> <nil> <nil> map[] [] <nil> false}
```

**Comment by tajtiattila** [comment]
@lindner When I tried sha-224 a few weeks ago it worked after uploading a new blob (with sha-224). This ensures that the signer is present with the currently preferred hash, which is sha-224. Perhaps this is still required for sha-224 to work.

**Comment by mpl** [comment]
ok, looking into it.

**Comment by mpl** [comment]
@lindner by any chance, would you happen to have a short-form (8 chars, e.g. "A9CB8BB2") for your identity, in your server-config.json file?
If yes, that's most likely the reason, so can you then please retry with the full size (16 chars, e.g. "62B585F5A9CB8BB2")?

When I worked on that change I did everything with the long-form for simplicity and that's why it's now biting us. I'll see about how to make everything consistent on that matter, but I'm wondering if that's worth the pain, and if we should not rather detect on startup that it is the short form and tell the user to fix their config with the long form.

**Comment by tdilo** [comment]
@mpl thanks, this solved my obscure problem at least - I was still debugging and waiting for a `-reindex` to complete. My instance started up without errors after editing the config to migrate from owner key sha1 to the new format, but the web UI only displayed the folder icon and all queries returned null values. I changed my config to the long-form key ID and everything is fine again.

I think aborting with an error when the config is in the old format (no owner object present, only the key hash string) and when a short-form key ID is detected would be the best approach.

**Comment by mpl** [comment]
PTAL: https://camlistore-review.googlesource.com/c/camlistore/+/14266

**Comment by lindner** [comment]
Can confirm that https://camlistore-review.googlesource.com/c/camlistore/+/14266 fixed this issue for me.
