### ISSUE TITLE
internal/fakefsnotify: incorrect statement in package comment

### ISSUE THREAD

**Issue by shurcooL** [perkeep/perkeep#1052]
I noticed the godoc for [`perkeep.org/internal/fakefsnotify`](https://godoc.org/perkeep.org/internal/fakefsnotify) package says:

> Obviously the 'gopherjs serve' command (which normally relies on fsnotify) is not expected to work when gopherjs is built with fakefsnotify.

This isn't true, `gopherjs serve` never uses fsnotify and works just fine without it. It always compiles the latest code from disk on every HTTP request, so all that's needed is to refresh the browser page.

fsnotify is only used by GopherJS when the `--watch` "watch for changes to the source files" flag is used, and that flag applies only to `gopherjs build` and `gopherjs install` commands.

So, perhaps the text should be changed to say something like this instead:

> The --watch flag (which normally relies on fsnotify) is not expected to work when gopherjs is built with fakefsnotify.

**Comment by lindner** [comment]
Looks like fakefsnotify is totally unused.  I think that happened in a recent gopherjs update.

I wonder if we should just remove it?

**Comment by mpl** [comment]
yeah with the move to dep we reverted to using the "non-hacked" version of gopherjs, so i think we can drop fakefsnotify.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14106
