### ISSUE TITLE
Manual Synchronisation via P2P as Packets

### ISSUE THREAD

**Issue by gdeverlant** [perkeep/perkeep#1055]
I would like to know if it is possible via my app to do some manual synchronisation based on the data that each peer wants to host on the p2p network. from my Video Editor instead of letting Perkeep to do synchronisation via HTTPS or HTTP... I would like to go through my p2p network and only synchronise specific Blobs with their relations.

How can I do that ?

**Comment by bradfitz** [comment]
Which p2p network? We don't support any NAT busting, UDP, P2P, or DHT at the moment.

So short answer is "no", unless you build it yourself or add it to Perkeep.

**Comment by gdeverlant** [comment]
No I'm using RTMFP for p2p part of my Video Editor and I would like to pin some Blobs between many peers so that they host the same data. I'm communicating with each peer in realtime via UDP(Punchole) and I wanted to know how could I from my app ask partial synchronisation or full synchronisatoin without going through the normal internet.

**Comment by bradfitz** [comment]
> Can Perkeep pack a bunch of Blobs inside one big binary data

Well, that part is done several parts of Perkeep already.

But we don't communicate over RTMFP or UDP.

You could download the blobs you need, tar them up, and send them over some channel of your own, and then untar them and insert the blobs.

If you have a concrete feature request, let us know, but otherwise I'm going to close this.

**Comment by gdeverlant** [comment]
This ticket is related with a feature request dated in ticket https://github.com/perkeep/perkeep/issues/21

**Comment by bradfitz** [comment]
There's not enough of a concrete plan here to keep open.

If you want to prototype something, that's fine, but we aren't going to track something we don't plan on doing.
