### ISSUE TITLE
Combine camtool, camput and camget into a single pk command

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1056]
The Basics
*  camget is replaced with "pk get"
*  camput is replaced with "pk put"

camtool has a much wider variety of subcommands:

```
  claims: Ask the search system to list the claims that modify a permanode.
  dbinit: Set up the database for the indexer.
  debug: Show misc meta-info from the given file.
  describe: Ask the search system to describe one or more blobs.
  discovery: Perform configuration discovery against a server.
  dumpconfig: Dump the low-level server config from its simple config.
  env: Return Perkeep environment information
  googinit: Init Google Drive or Google Cloud Storage.
  index: Synchronize blobs for all discovered blobs storage - indexer pairs.
  list: List blobs on a server.
  makestatic: Creates a static directory from a permanode set
  named-search-get: Get a named search's current value
  named-search-set: Create or update a named search
  packblobs: Pack related blobs together (migration tool)
  reindex-diskpacked: Rebuild the index of the diskpacked blob store
  search: Execute a search query
  searchdoc: Provide help on the predicates for search expressions
  sync: Synchronize blobs from a source to a destination.
  whoami: Show Perkeep identity information
```

These might require some extra thought.

We may want to consider using http://github.com/spf13/cobra -- it's used by gopherjs and other tools and has good support for arbitrary subcommands and flags.

**Comment by mpl** [comment]
I haven't looked at http://github.com/spf13/cobra , but in case you haven't seen pkg/cmdmain is what helps us make commands and subcommands.

**Comment by lindner** [comment]
Yeah, I saw cmdmain, it and cobra overlap on features, but not entirely.  I
do like that cobra can support multiple-sub commands.  cmdmain allows for
more extension hooks.

What do people thing about mapping camtool to

  pk admin <cmd>

?

**Comment by bradfitz** [comment]
> Yeah, I saw cmdmain, it and cobra overlap on features, but not entirely.

I'd prefer we just keep using ours if possible. It predates cobra anyway, and does what we need. Neither are very complicated. I suppose if we do nested levels and cobra is easier, I won't strongly object.

> What do people think about mapping camtool to `pk admin <cmd>`

I don't think many of the camtool commands are admin related. Like, `search` isn't, so `pk admin search` seems weird.

Maybe for some we could put them under admin or something.

Why not put everything under `pk`? To make `pk help` prettier?

**Comment by lindner** [comment]
The cobra+venom combination is interesting because it offloads a lot of
non-core complexity for flag, command and config management.

I'd also like to know what people think about Integrating all command line
tools including camlistore and mount into a single binary?

pk serve  <-- replaces camlistored
pk mount

This could also allow for devcam to be a pk+dev combo or devcam could just
be a wrapper around pk..

Thoughts?

**Comment by adamdecaf** [comment]
I never really understood the difference with, say, `camput` vs `camget`. I'd be in favor of merging those all into one binary.

I understand `devcam` and `camlistored` (`perkeepd`?) being separate binaries as they have usecases outside of what `pk` would.

**Comment by bradfitz** [comment]
We're not going to link the client code & server code together into one binary.

Likewise, we're not going to link the FUSE code together with anything.

As I said on your review (https://camlistore-review.googlesource.com/c/camlistore/+/14166#message-2d46bda2c2584b16bf05caa9f7c419c2e15386e6) the plan was roughly to be like git, where "pk" could dispatch "pk foo" to "pk-foo".

Maybe we could add some special cases like "pk serve" to call other binary names, but I think "pk" should probably remain a client tool, and the server should be its own binary name.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14606

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/15518
