### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1070]
Consider adding a code of conduct for Perkeep.

We can either reference the existing Google code of conduct:

https://opensource.google.com/conduct/

Or consider adding our own.

**Comment by bradfitz** [comment]
Reference Google's. We don't want to write our own.

**Comment by lindner** [comment]
Using Google's is fine with me.

What's our governance model for decisions like this?  I guess I can use lazy consensus?

"If there are no objections by Mar 3rd, 2018 to this decision I will send a CL adding a one-paragraph section to README.md noting that we use the Google Code of conduct and directing any issues to opensource@google.com"

**Comment by bradfitz** [comment]
> What's our governance model for decisions like this? 

I don't know. We don't have one. BDFL? Lazy consensus works usually, but for things like CoC I'm fine with just decreeing that we have one.

**Comment by mpl** [comment]
> "If there are no objections by Mar 3rd, 2018 to this decision I will send a CL adding a one-paragraph section to README.md noting that we use the Google Code of conduct and directing any issues to opensource@google.com"

Shouldn't that be sent to the ML as well? Just to be clear, I don't care. Just a remark/question.

**Comment by lindner** [comment]
https://camlistore-review.googlesource.com/c/14686/

Email sent to mailing list with lazy consensus for Mar 19.

**Comment by ivanov** [comment]
My only concern with the patchset is that it does not name a Project Steward and contact information. Presumably,  `opensource@google.com` is not the appropriate point of contact for folks who wish to report code of conduct-related problems to perkeep.

**Comment by lindner** [comment]
The Google Opensource folks are willing to intervene on these matters at
this time.  The Perkeep project currently falls under the Google umbrella.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14726

**Comment by willnorris** [comment]
`opensource@google.com` comes to me (and a few others), so if I ever got any reports, I'd end up reaching out to Brad and company anyway.
