### ISSUE TITLE
Use a wildcard cert to make it easier to deploy hosted perkeep

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1072]
Let's Encrypt supports wildcard certs now:

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by bradfitz** [comment]
I don't see how this helps anything, or how this would even work.

All these users have their own IP addresses. We don't proxy all their traffic.

**Comment by lindner** [comment]
The use case I was considering was making the camlistore.net support
easier.  But yeah, using a shared cert is probably not a great idea.

**Comment by bradfitz** [comment]
Okay, closing.
