### ISSUE TITLE
server/camlistored: let Let's Encrypt http-01 port be configurable

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1078]
as per TODO

**Comment by mpl** [comment]
@bradfitz I forget, but I think you had already started on that?

**Comment by bradfitz** [comment]
I'd started, but got distracted with other brokenness so I never actually did anything for this bug.

**Comment by zoranzaric** [comment]
As discussed on IRC I started implementing this.

**Comment by zoranzaric** [comment]
My current problems are:

### New introduced `listenLetsEncrypt` not beeing populated into config

In [`server/camlistored/camlistored.go` Line 249](https://github.com/zoranzaric/perkeep/blob/iss1078/server/camlistored/camlistored.go#L249) I currently print the config and it doesn't contain my new introduced config option.

### Config parsing error

After adding [`pkg/serverinit/genconfig.go` Line 1073 and 1074](https://github.com/zoranzaric/perkeep/blob/iss1078/pkg/serverinit/genconfig.go#L1073):

```go
f conf.ListenLetsEncrypt != "" {
	low["listenLetsEncrypt"] = conf.ListenLetsEncrypt
}
```

I get this error: `Error parsing config: configuration error in root object's keys: Unknown key "listenLetsEncrypt"`.

Can anybody mentor me on these problems?

**Comment by mpl** [comment]
You get that error because all configuration options need to be "consumed" before config.Validate is called. So whichever part of Perkeep that is going to make use of listenLetsEncrypt needs to call config.OptionalString("listenLetsEncrypt") or something like that to get the actual value, and signal in the config that this key has been used/retrieved by something.

**Comment by zoranzaric** [comment]
Strange.. I do that here: https://github.com/zoranzaric/perkeep/blob/iss1078/pkg/server/app/app.go#L352

**Comment by zoranzaric** [comment]
Thanks for the hint. that fixed it.  I'll send the PR now.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14866

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17586

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17626
