### ISSUE TITLE
pkg/index/sqlite: tests are failing

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1085]
Because of some sha1 vs sha224 shenanigans.
It went unnoticed since our CI does not run tests with "with_sqlite" on. It probably should?

**Comment by bradfitz** [comment]
Might as well.

I don't see a downside. It's off by default for users, but if we can configure the CI to have it available, seems good to have more test coverage.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18386
