### ISSUE TITLE
internal/images: make docker container for heiftojpeg

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1087]
with just a static binary of heiftojpeg in an alpine container. We can use a multistage Dockerfile and have the first stage be Debian and then in the second stage copy the static binary to Alpine.

Then maintain it in dockerhub or gcr.io (or cloud bucket?).

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/15226

**Comment by mpl** [comment]
yeah that's pretty much the output I was getting too.
I've read a bunch of things (that link included), and I've tried various combinations of:

set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
set(BUILD_SHARED_LIBRARIES OFF)
set(CMAKE_EXE_LINKER_FLAGS "-static -static-libgcc -static-libstdc++")

to no avail. I think they pretty much do the same thing as running with --static anyway. hmm except there was a slight difference whether I included -static-libgcc -static-libstdc++ , but I'm not sure.
I've think I've gotten rid of some of the undefined errors by installing 'libmagickwand-dev libmagickwand-6-headers' as well, but I still got a ton.

also, jsyk, I first started with the Aboriginal Linux toolchain, like we do for djpeg-static, but apparently that compiler is not c++11 compliant, so cmake rejected it.

**Comment by bradfitz** [comment]
Actually, if we just build with Alpine in the first layer, we don't need to worry about a static binary and we can have the Alpine in the second layer just be shared libraries + heiftojpeg.

**Comment by bradfitz** [comment]
e.g.

```
FROM alpine:3.7
RUN apk add --no-cache git cmake alpine-sdk imagemagick-dev

WORKDIR /tmp
RUN mkdir -p github.com/pushd
WORKDIR github.com/pushd
RUN git clone https://github.com/pushd/heif/
WORKDIR heif
RUN git reset --hard 1062c752b0465aabc0f6001d1c20da076bf514f5
WORKDIR build

RUN apk add --update

RUN cmake ..
RUN make
```

**Comment by bradfitz** [comment]
@mpl, this works and is 16.5MB:

```
# Copyright 2018 The Perkeep Authors.
FROM alpine:3.7
RUN apk add --no-cache git cmake alpine-sdk imagemagick-dev

WORKDIR /tmp
RUN mkdir -p github.com/pushd
WORKDIR github.com/pushd
RUN git clone https://github.com/pushd/heif/
WORKDIR heif
RUN git reset --hard 1062c752b0465aabc0f6001d1c20da076bf514f5
WORKDIR build

RUN apk add --update

RUN cmake ..
RUN make
WORKDIR ..

RUN apk add --no-cache bash

FROM alpine:3.7

COPY --from=0 /tmp/github.com/pushd/heif/Bins/heiftojpeg /usr/local/bin

COPY --from=0 /usr/lib/libMagick++-7.Q16HDRI.so.3 /usr/lib/libMagick++-7.Q16HDRI.so.3
COPY --from=0 /usr/lib/libMagickCore-7.Q16HDRI.so.4 /usr/lib/libMagickCore-7.Q16HDRI.so.4
COPY --from=0 /usr/lib/libstdc++.so.6 /usr/lib/libstdc++.so.6
COPY --from=0 /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so.1
COPY --from=0 /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
COPY --from=0 /usr/lib/libMagickWand-7.Q16HDRI.so.4 /usr/lib/libMagickWand-7.Q16HDRI.so.4
COPY --from=0 /usr/lib/liblcms2.so.2 /usr/lib/liblcms2.so.2
COPY --from=0 /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so.1
COPY --from=0 /usr/lib/libfreetype.so.6 /usr/lib/libfreetype.so.6
COPY --from=0 /usr/lib/libbz2.so.1 /usr/lib/libbz2.so.1
COPY --from=0 /lib/libz.so.1 /lib/libz.so.1
COPY --from=0 /usr/lib/libltdl.so.7 /usr/lib/libltdl.so.7
COPY --from=0 /usr/lib/libgomp.so.1 /usr/lib/libgomp.so.1
COPY --from=0 /usr/lib/libexpat.so.1 /usr/lib/libexpat.so.1
COPY --from=0 /usr/lib/libpng16.so.16 /usr/lib/libpng16.so.16

ENTRYPOINT ["/usr/local/bin/heiftojpeg"]
```

Building it:

```
$ docker build --quiet --tag=heiftojpeg . && docker run heiftojpeg  -h
sha256:f10e22770957117bcaf5cdbc1781cde18684a048c2a71f28112ed98cd069829b
Usage: heiftojpeg [-v] [-s <max_dimension>] <input.heic> <output.jpg>
```

**Comment by bradfitz** [comment]
```
$ docker image inspect heiftojpeg | jq '.[0].Size'
16462085
```

**Comment by mpl** [comment]
Neat trick.
Just take over the CL with it then?

**Comment by mpl** [comment]
I'm surprised you don't need exiftool though. Maybe it's only called when resizing?

**Comment by bradfitz** [comment]
Why don't you continue with this? You can put all the pieces together.

**Comment by mpl** [comment]
sure, I was just giving you "author's priority" since you did most of the recent work.
