### ISSUE TITLE
make.go: does not support multiple entries in GOPATH

### ISSUE THREAD

**Issue by tdilo** [perkeep/perkeep#1101]
When using a GOPATH environment variable with multiple entries, `make.go` fails to build as it constructs path and file names by simple concatenation. Errors vary depending on operating system.

On Linux, the build stops with a panic due to nil pointer dereference in
https://github.com/perkeep/perkeep/blob/c193a87ae1/make.go#L405 (`fi2` is nil).

On Windows, the build aborts with:
`CreateFile C:\go1;C:\go2\bin\js.js: The filename, directory name, or volume label syntax is incorrect.`

See https://golang.org/cmd/go/#hdr-GOPATH_environment_variable
> The GOPATH environment variable lists places to look for Go code. On Unix, the value is a colon-separated string. On Windows, the value is a semicolon-separated string.

I think the correct behavior would be to simply use the first entry of GOPATH, which is the default for `go get` and such as well.

**Comment by bradfitz** [comment]
Thanks for the report.

FWIW, this my pet peeve too. I even proposed https://github.com/golang/go/issues/18119 (which is accepted but unimplemented)

/cc @mpl

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/15515

**Comment by tdilo** [comment]
Tested the CL on my Windows machine, works as intended.
