### ISSUE TITLE
ui: surface search query errors to user

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1116]
If you do a UI search for "x:y", the user sees an empty search result and no error message.

But in the server logs:

```
2018/04/25 18:23:14 Sending error 500 to client for: Invalid SearchQuery: Error parsing search expression "x:y": Unknown search predicate: "x:y" at position 0, token: "x:y"
```

Fix that and show it to the user.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/15866

**Comment by euank** [comment]
I don't think this one is really fixed until https://github.com/go4org/go4/pull/37 is merged and the vendor version metadata (e.g. Gopkg.lock or go.mod) is updated appropriately.

Right now, perkeep master has a vendor folder which isn't reproducible with `dep ensure`, and I will be totally unsurprised if the vendor change in the above CL gets lost the next time someone runs `dep ensure`.

**Comment by mpl** [comment]
Yes we know. I'm waiting for Brad to approve the PR, so I can land it and then sync Perkeep from upstream.
