### ISSUE TITLE
ui: ref query with blobref prefix in search bar sets URL to bogus value

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1119]
If you do a search in the UI for:

ref:sha1-f

... it'll change the URL to:

   http://server/ui/sha1-f

... and do nothing. Reload the page and you get an illegal URL message.

I think something in the UI is assuming that "ref:xxxx" always means that xxxx is a full blobref, and not a prefix.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18606
