### ISSUE TITLE
Twitter importer instructions now out of date

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1130]
The Twitter "Create an app" flow is slightly different and they renamed some things.

We should update our Twitter importer's in-app docs.

Notably, we need to clarify which since-renamed fields on Twitter's site go into our "Client ID" and "Client Secret" fields.

/cc @mpl

**Comment by NiklasMerz** [comment]
We should also mention the twitter option. I never would have found it, if I had not started working on the importer.

**Comment by mpl** [comment]
@NiklasMerz what option?

**Comment by NiklasMerz** [comment]
Importing from zip is explained in importer/twitter/twitter.go, but not in the import settings page for example. As a normal user I would not have know that you can do this:

```
// acctAttrTweetZip specifies an optional attribte for the account permanode.
// If set, it should be of a "file" schema blob referencing the tweets.zip
// file that Twitter makes available for the full archive download.
// The Twitter API doesn't go back forever in time, so if you started using
// the Perkeep importer too late, you need to "pk-put file tweets.zip"
// once downloading it from Twitter, and then:
//   $ pk-put attr <acct-permanode> twitterArchiveZipFileRef <zip-fileref>
// ... and re-do an import.
```

We could add a note about that option on the import page for example.

**Comment by mpl** [comment]
sure

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17726
