### ISSUE TITLE
 unknown high-level configuration parameter: "dbNames" 

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1133]
User reports:

```
$ ./perkeepd 
2018/04/29 19:15:43 Starting perkeepd version 2018-04-28-b0c1faccfe; Go go1.10.1 (linux/amd64)
Error loading config file: unknown high-level configuration parameter: "dbNames" in file "/home/ubuntu/.config/perkeep/server-config.json"
```

@mpl, did we remove that but not change the default server config that we write?

**Comment by mpl** [comment]
@NorthDecoder I've just removed my $HOME/.config/perkeep , then I started ./perkeepd , and I could not reproduce. The generated config file looks ok to me. Could you give me the steps to reproduce the issue please?

**Comment by NorthDecoder** [comment]
Retried install in the same workspace by re-cloning code, now `go run make.go` getting a new error, which I did not get before: `Out of Memory`.  This workspace only has arbitrary limit of 512Mb, I will switch to server with more available memory, then continue testing.

**Comment by mpl** [comment]
pushing the milestone since 0.10 is out

**Comment by NorthDecoder** [comment]
I switched from the Cloud9 virtual machine with limited memory, to testing on a desktop and the install works okay.
```
$ uname -a
Linux machinename 4.13.16-100.fc25.i686+PAE #1 SMP Mon Nov 27 20:26:05 UTC 2017 i686 i686 i386 GNU/Linux
$ free -ht
              total        used        free      shared  buff/cache   available
Mem:           2.0G        1.1G         57M        317M        801M        601M
Swap:          2.1G         17M        2.1G
Total:         4.0G        1.1G        2.1G

```
I guess some kind of prerequisite README notes would advise against attempts to do the impossible, plus some quick check during the first part of the `go run` install to see if there will be enough memory to actually do the install.

Thanks for looking over my shoulder at my difficulty with the install during linuxfestnw; if you think we are done with this please feel to close it.

**Comment by bradfitz** [comment]
Thanks for the update. Will close.
