### ISSUE TITLE
doc: installation instructions misleading

### ISSUE THREAD

**Issue by nf** [perkeep/perkeep#1135]
The download page says:

> git clone https://camlistore.googlesource.com/camlistore

but doesn't say where to clone it. Then if you `go run make.go` it tells you to put it in $GOPATH/src/perkeep.org. The clone instructions should mention this in the first place.

**Comment by bradfitz** [comment]
Whoops. Thanks.

**Comment by bradfitz** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/15826
