### ISSUE TITLE
Old configuration directory detected

### ISSUE THREAD

**Issue by skz169** [perkeep/perkeep#1150]
Perkeep launched for the first time. Both configuration directories are created automatically.
```
c:\Users\s\AppData\Local\perkeep>perkeepd.exe
2018/05/06 12:31:05 Starting perkeepd version 0.10, 2018-05-02-0cbe4d5e05; Go go1.10.2 (windows/amd64)
2018/05/06 12:31:05 Generating template config file C:\Users\s\AppData\Roaming\Perkeep\server-config.json
Error: old configuration directory detected. Not running until it's moved.
Rename C:\Users\s\AppData\Roaming\Camlistore to C:\Users\s\AppData\Roaming\Perkeep
```

**Comment by willnorris** [comment]
The last line in the message tells you what to do:

> Rename C:\Users\s\AppData\Roaming\Camlistore to C:\Users\s\AppData\Roaming\Perkeep

You will likely also need to modify `identitySecretRing` in `server-config.json` to reflect the new directory name.

**Comment by bradfitz** [comment]
As @willnorris said, see the last line of the error message for how to fix it.

But to clarify: is this your first time ever running Camlistore/Perkeep, or just your first time since running Perkeep since it was renamed from Camlistore? If the latter, this is expected. If the former, that's a bug and suggests we're still creating Camlistore files somewhere.

**Comment by willnorris** [comment]
(sorry, I deleted my message realizing that I misread the original report.  It sounded like this is happening on first launch, in which case it definitely would be a bug.  I've yet to try to reproduce yet)

**Comment by skz169** [comment]
I didn't run Camlistore or Perkeep before. Even if I delete both empty directories manually this error occures.

**Comment by bradfitz** [comment]
Interesting! Definitely a bug then. Will try to fix tonight.

**Comment by bradfitz** [comment]
Ah, I see the bug. And it's in a Windows-only path. We ran all the tests on Windows before release, but apparently there's not a test for this? I'm surprised, since we do have an integration test that should've caught it.

I'll make sure there's test coverage for this too when I fix.

**Comment by bradfitz** [comment]
Reproduced it on my Windows machine. Fix mostly done, but will wait for new tests until I send it out.

**Comment by skz169** [comment]
Thanks Brad. Waiting for a new release.

**Comment by bradfitz** [comment]
Sent https://camlistore-review.googlesource.com/#/c/camlistore/+/16146 and tested on Windows, both that it cleans up a messed config, and that it starts up correctly when neither directory exists.

No automated tests yet. Coming.

**Comment by bradfitz** [comment]
Tests added.

**Comment by bradfitz** [comment]
Reopening for cherry-pick to 0.10 branch + new 0.10.1 release.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/16289
