### ISSUE TITLE
server/perkeepd: errors from WriteDefaultConfigFile are ignored

### ISSUE THREAD

**Issue by bobg** [perkeep/perkeep#1154]
If `WriteDefaultConfigFile` returns an error (like "you have to rename var/camlistore to var/perkeep") then the config file won't be written but `loadConfig` will continue to the `serverinit.LoadFile` line anyway. The resulting no-such-file error masks the true problem.

https://github.com/perkeep/perkeep/blob/d50667a1788f67a91f267ca09e0e51dd39fe6042/server/perkeepd/camlistored.go#L194-L196

**Comment by bradfitz** [comment]
Whoops. Thanks & sorry. Fixing coming right up.

**Comment by bradfitz** [comment]
Reopening for cherry-pick.

/cc @mpl

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/16288
