### ISSUE TITLE
make.go: -embed_static=false is not respected because of previous builds

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1157]
If make.go was previously run at least once with -embed_static=true, then the zembed* files have been generated. And since we don't work from a temp dir from scratch anymore, then in subsequent builds the zembed* files will still be present, and they will be included in the build, even if -embed_static=false is used.

So when -embed_static=false is used, we need to either start by removing all zembed* files, or maybe find a way for the compilation to ignore them.

**Comment by bradfitz** [comment]
> or maybe find a way for the compilation to ignore them.

Seems like a good use of https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by bradfitz** [comment]
(especially now that Go 1.10 has proper build caching that includes respecting build tags)

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/16546

**Comment by mpl** [comment]
good call, that was easy.
