### ISSUE TITLE
Docker installation on a Raspberry Pi 3B

### ISSUE THREAD

**Issue by raphaelyancey** [perkeep/perkeep#1158]
I'm facing this error when trying to build the image on a Raspberry Pi 3B:
```
[...]
Step 33/43 : RUN go run make.go --sqlite=true -v
 ---> Running in 14e0ee5e1d98
/bin/sh: 1: go: Exec format error
The command '/bin/sh -c go run make.go --sqlite=true -v' returned a non-zero code: 2
```

I tried to set `ENV GOOS linux` `ENV GOARCH=arm` and `ENV GOARM=7` in the Dockerfile before the buggy line but it doesn't change anything.

I'm running Raspbian Stretch 9.4 and Docker 18.05.0-ce.

**Comment by bradfitz** [comment]
The Dockerfile assumes linux/amd64 a few lines up from there:

```
RUN wget -O go.tgz https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz
```

That's why you're seeing "Exec format error". Your ARM kernel doesn't like the x86 "go" binary running "go run make.go".

Want to send a fix?

**Comment by raphaelyancey** [comment]
Oh thanks, didn't see that. I'll look into it and send a PR.

**Comment by mpl** [comment]
> For some reason, Go couldn't compile on the Raspberry Pi so I used the golang image directly.

Not enough memory, maybe ?

**Comment by bradfitz** [comment]
Or test timeouts.

Did you run `all.bash` or `make.bash`?

**Comment by raphaelyancey** [comment]
@mpl I eventually faced this problem but solved it by freeing some memory.

I think the problem was that the [sources for 1.10.2](https://golang.org/dl/#stable) are only available for armv6l and arm64 and not armv7, which is somehow available in the official golang image. I moved on after the installation and forgot what it was exactly.

**Comment by bradfitz** [comment]
@raphaelyancey, the "source" downloads of Go aren't for any platform at all.. they're just source and you can compile wherever. Are you talking about binary downloads? But you said above "Go couldn't compile on the Raspberry Pi".

**Comment by raphaelyancey** [comment]
@bradfitz My bad, I meant the binaries. Replacing with armv6l binary in the original Dockerfile didn't make it, and I failed building go from source on the Pi (first because of the free memory requirement, then for something else I don't remember). Then I quickly moved on with the official image that is working and didn't dig deeper into the problem.

**Comment by mpl** [comment]
@raphaelyancey I lost track. Is the issue fixed for you now?

**Comment by raphaelyancey** [comment]
@mpl Yes we can close, thanks. Not really fixed but bypassed.
