### ISSUE TITLE
"pk get" has description of "pk put"

### ISSUE THREAD

**Issue by pstuifzand** [perkeep/perkeep#1159]
The Describe method of getCmd has the same description pk put.

https://github.com/perkeep/perkeep/blob/e22801a8ab89d948c9ac3d9adb298bfdbb35d5be/cmd/pk/get.go#L39

**Comment by mpl** [comment]
@bradfitz we probably want to add that one to the 0.10.1 release too, right?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/16286
