### ISSUE TITLE
./pkg/client and ./pkg/serverinit are broken

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1171]
https://travis-ci.org/perkeep/perkeep/builds/380513966

It looks like https://camlistore-review.googlesource.com/c/camlistore/+/16486 broke them.

@bradfitz do you want to take care of it?

**Comment by bradfitz** [comment]
Whoops, I sent that CL as an example but never ran tests on it. When I found it back a few days later I had forgotten it was just an example.

Fixing.

**Comment by bradfitz** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/16766
