### ISSUE TITLE
Update everything for Gerrit move

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1176]
Our new Gerrit instance is:

https://perkeep-review.googlesource.com/q/status:open

Tracking bug to update docs & tooling.

We probably need devcam or something to fix git origins.

And make.go.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/16886

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/#/c/perkeep/+/16906
