### ISSUE TITLE
importer/pinboard Pinboard importer does not support auto mode

### ISSUE THREAD

**Issue by NiklasMerz** [perkeep/perkeep#1182]
The pinboard importer does not support running in auto mode. Is it possible to do that?

I would love to contribute that.

**Comment by mpl** [comment]
> The pinboard importer does not support running in auto mode. Is it possible to do that?

I don't see why not. you mean running every N minutes, don't you? 

> I would love to contribute that.

Sure, you're welcome to do so (if it does not already...).

**Comment by NiklasMerz** [comment]
> I don't see why not. you mean running every N minutes, don't you?

Yes i would like to run it regularly like the twitter importer

> Sure, you're welcome to do so (if it does not already...).

I will try my best to figure out how to do that. For question I will bother the mailinglist :)

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/16986
