### ISSUE TITLE
importer: add a Mastodon/Pleroma importer?

### ISSUE THREAD

**Issue by DeeUnderscore** [perkeep/perkeep#1183]
Hi there. I'd like to write a Perkeep importer for the common API shared by Mastodon and Pleroma.

[Mastodon](https://joinmastodon.org/) and [Pleroma](https://pleroma.social/) are two microblogging social network server projects which can federate over ActivityPub. Both use the same API (originated with Mastodon), and client software is generally compatible with either.

The importer would store a user's posts along with media attachments, essentially the same way that the Twitter importer does it. 

Would there be any interest in a patch for this? Or, more generally, any interest in this?

**Comment by bradfitz** [comment]
Totally!

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/17366
