### ISSUE TITLE
camlistore-commits email list not receiving mail since April 23

### ISSUE THREAD

**Issue by lindner** [perkeep/perkeep#1188]
Looks like these emails are sent with mailgun via

https://github.com/perkeep/perkeep/blob/master/website/pk-web/email.go

So might just be a website configuration issue.

**Comment by mpl** [comment]
thx, i'll look into it

**Comment by mpl** [comment]
weird, the mailgun interface shows them as delivered
![screenshot](https://user-images.githubusercontent.com/626071/41373882-e01ddb8a-6f51-11e8-8d60-0c0b21824268.png)

**Comment by lindner** [comment]
Maybe the mailing list is putting them in the moderation queue?

**Comment by mpl** [comment]
yeah, I've asked Brad to make me a manager on there (which I am not yet) so I could check things like that.

**Comment by mpl** [comment]
It was a weird combination. the sender address was wrong, but mailgun was still happily sending them.
And the messages were not showing up as pending in the google group interface, _until_ i added manually the noreply@perkeep.org member. Then they showed up as pending, so then I had to reallow that sender again for some reason.

Anyway, this does not seem to be necessary now, but it still probably is the proper thing to do:
https://perkeep-review.googlesource.com/#/c/perkeep/+/17286

**Comment by mpl** [comment]
Yep, they're showing up again now.
