### ISSUE TITLE
devcam hook: broken with git commit --amend

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1191]
$ git commit --amend internal/geocode/geocode.go server/perkeepd/perkeepd.go

fatal: There is nothing to exclude from by :(exclude) patterns.
Perhaps you forgot to add either ':/' or '.' ?
Trailing whitespace detected, you need to clean it up manually.

Bug most likely introduced at https://perkeep-review.googlesource.com/c/perkeep/+/17146

**Comment by mpl** [comment]
@euank Please let me know if you want to look into fixing it. Otherwise I'll just revert it, and fix it properly later.

**Comment by euank** [comment]
What version of git are you using, @mpl? `git commit --amend` works fine for me with using those hooks on master.

**Comment by mpl** [comment]
@euank yeah, I'm on git version 1.9.1

**Comment by mpl** [comment]
@euank no harm done (I just reverted the change locally so I could keep on working yesterday), so no worries.
