### ISSUE TITLE
Determine the fate of 'asserts' package

### ISSUE THREAD

**Issue by euank** [perkeep/perkeep#1192]
Currently, perkeep.org/pkg/test/asserts contains a warning not to use it in its current state.

I think we have a few options for moving forwards:

1. Replace with an existing other library (I think testify/assert is the most popular)
2. Improve the asserts package; fix whatever issue resulted in its deprecation and begin using them again
3. Don't use any general asserts library, rather inline the checks in tests that use asserts now and create package-specific assertions as needed

Option 1 has the advantage of us maintaining the least code while still being able to remove extra noise from tests. It has the disadvantage of most assert libraries being a pile of reflection which is fragile at times.
Option 2 is only viable if we can actually enumerate the blocking issues with the current asserts package. As far as I can tell, this hasn't been done.
Option 3 may be difficult to automate as easily as 1 or 2, though it's still technically possible. We won't have such helpers available which is a plus or minus depending on taste.

Regardless what we do, I think actually clarifying the issues with the `asserts` package as it exists today is the first step to deciding what to do next.

If the only issue is the `what` messiness, that can now be fixed with `t.Helper`

**Comment by mpl** [comment]
Related: https://perkeep-review.googlesource.com/c/perkeep/+/16926
