### ISSUE TITLE
Feature request: maildir and mbox imports

### ISSUE THREAD

**Issue by ClashTheBunny** [perkeep/perkeep#1197]
I have a bunch of old backups of mail that I'd like to get stored in one searchable place.  Perkeep seems like it would be a great fit.  I don't need to send mail or understand much about the messages, but I would want all the metadata and mine attachments.

Does this seem like something others would be interested in, or is there another thing that I should use?

**Comment by mpl** [comment]
maybe a dup of #465 though?

**Comment by ClashTheBunny** [comment]
This could be a dup.  I do think this is partly in addition to the ongoing importing of #465, but would be the same data structures and search associated with it.

**Comment by bradfitz** [comment]
Yes, closing as a dup. Let's consolidate discussion in #465, which I've retitled as a start.
