### ISSUE TITLE
pkg/index tests are failing

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1199]
https://travis-ci.org/perkeep/perkeep/builds/408296704

Looks like it was broken at 13a8e948950460a26de6274ce037b3b0b7ed2d38

**Comment by mpl** [comment]
@euank Let me know if you want me to look into it or if you're on it please.

**Comment by euank** [comment]
Apologies for my carelessness, it looks like I forgot to commit a change I had locally which let tests pass. I've submitted https://perkeep-review.googlesource.com/c/perkeep/+/17766 for this.

I think this is also a good argument for https://github.com/perkeep/perkeep/issues/1198... we should be catching these sorts of silly mistakes before merge, not after.
