### ISSUE TITLE
Constant time comparison for user/password check

### ISSUE THREAD

**Issue by psilva261** [perkeep/perkeep#1205]
The check for http auth uses the normal string comparison operator: https://github.com/perkeep/perkeep/blob/master/pkg/auth/auth.go#L245

Go standard library provides a special function that does comparison in constant time: https://golang.org/pkg/crypto/subtle/#ConstantTimeCompare

Already mentioned this in the weekly irc, so I'd like to prepare a pull request soon.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18026
