### ISSUE TITLE
Geocoding should use viewport

### ISSUE THREAD

**Issue by vron** [perkeep/perkeep#1210]
Currently geocoding will only work if a bounds property is returned by google geo api. However, according to https://developers.google.com/maps/documentation/geocoding/intro bounds is optionally returned and I have indeed come across quite a few cases where perkeep does not work wit “loc” searches due to this - eg searching for “hardangervidda” etc.

I suggest to change the geocoding code to always return a resul lt iv a viewpoint is defined, overwriting it with bounds if defined - instead of requiring a bounds to be defined as it currently is.

**Comment by vron** [comment]
If agreed/accepted I ca fix this as a first contribution.

**Comment by vron** [comment]
Sent https://perkeep-review.googlesource.com/c/perkeep/+/18246 as it might be easier to discuss in code then in text...

**Comment by mpl** [comment]
SGTM

**Comment by vron** [comment]
Closing since e6fb16557fdc28d6b2d45080a258233c3254be48 was merged.
