### ISSUE TITLE
Incorrect truncation of files in the FUSE filesystem

### ISSUE THREAD

**Issue by kseistrup** [perkeep/perkeep#1218]
I get surprising results when I try to write to already existing files in the FUSE filesystem, but the example below sums it up nicely:

```sh
$ # Perkeep FS is mounted at ~/Perkeep
$ mkdir -p ~/Perkeep/roots/test && cd $_
$ printf '%s\n' {1..3} > seq.txt  # let's create a file with numbered lines
$ cat seq.txt
1
2
3
$ # so far, so good
$ echo x > seq.txt  # seq.txt should now contain a single line: x
$ cat seq.txt
x
2
3
$ # wtf?
```

```sh
$ perkeepd --version
perkeepd version: master, 2018-09-14-ca7f2e57e3
Go version: go1.11 (linux/amd64)
```

**Comment by kseistrup** [comment]
Any news here?

**Comment by mnzaki** [comment]
I'm hitting this consistently. Make a file, make it shorter, you get bytes from the previous version(s).

**Comment by cfiske** [comment]
I see similar behavior with `pk get` as well. If I get a blob and output to a file, then get a smaller blob and output to the same file it still has the extra bytes from the first blob.

**Comment by kseistrup** [comment]
@cfiske My usecase for perkeep was the filesystem. And since this bug renders the filesystem useless, unless you take great care to _always_ overwrite a file with another file of same or bigger size, I stopped using perkeep literally years ago.

**Comment by MichaHoffmann** [comment]
Hey @kseistrup @cfiske 

I think i debugged the issue truncation issue and opened #1590 to fix it.

**Comment by kseistrup** [comment]
@MichaHoffmann Amazing to see activity on this issue after such a long time! :fireworks:
