### ISSUE TITLE
Simple HTTP Authentication token is lost when clicking "Map" tab

### ISSUE THREAD

**Issue by khimaros** [perkeep/perkeep#1221]
I bumped into this bug a few months back but recently began experimenting with Perkeep again and discovered that it was still an issue.

I'm using Nginx as a reverse proxy for Perkeep. I authenticate using Simple HTTP Auth (managed by Nginx) and can navigate around the Perkeep UI, click on blobs, view/edit metadata, access the publisher frontend, etc.

However, when I click the "Map" tab, I'm prompted for Simple HTTP Auth credentials. After entering the correct credentials, I'm immediately prompted again for them. The only way to exit this loop is to press "Cancel" and then navigate manually back to the base URL.

I'm using Chrome as my browser.

I'm using a simple JSON config and have Perkeep native auth disabled:

```
    "listen": ":3179",
    "baseURL": "https://{{mydomain}}.com",
    "auth": "none",
```

I have websocket proxying enabled in Nginx. Searches and dynamic search updates work fine. However, the credentials seem to be wiped immediately after attempting a request to `wss://{{mydomain}}.com/my-search/camli/search/ws?authtoken=OmitAuthToken` which causes the subsequent request to `https://{{mydomain}}.com/ui/` to prompt for user/pass.

These are the relevant bits for websocket proxying:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;
```

**Comment by khimaros** [comment]
The same also seems to happen when selecting one or more items and then clicking "Share" from the context menu.

**Comment by mpl** [comment]
@khimaros Can you please confirm that websockets are the source of the problem, or is it speculation? For example, if you remove all ws support from your nginx conf, do you still see the auth problems with the Map aspect and the "Share" feature?

Also, isn't it important to upgrade the connection only when needed, as it's done in https://perkeep-review.googlesource.com/c/perkeep/+/17866/1/misc/docker/synology/perkeep/scripts/postinst ?

**Comment by khimaros** [comment]
@mpl, I do have the 'map' for connection upgrade but omitted for brevity. The issue remains when disabling the websocket bits in my nginx config.

Initial page load is "https://{{mydomain}}.com/" (301) followed by an "https://{{mydomain}}.com/ui/ (200).

I can navigate and search, resulting in a number of "wss://{{mydomain}}.com/my-search/camli/search/ws?authtoken=OmitAuthToken" (101). All requests have the following header:

Authorization: Basic {{keymaterial}}

I can also navigate to the "Importers" and other items in the Piggy menu. All have the same header.

Upon clicking "Share" there is a request to "https://{{mydomain}}.com/" with an incorrect Authorization header. It predictably results in a 401.

Request URL: https://{{mydomain}}.com/
Request Method: GET
Status Code: 401
accept: text/x-camli-configuration
authorization: Token OmitAuthToken

**Comment by mpl** [comment]
Ah yes, now that you mention Share again, it clicked for me where this is coming from. I'll fix soon.

**Comment by mpl** [comment]
@khimaros fyi, the problem is coming from the fact that Share, and the Map (and other features), are basically client requests implemented in Go, and they rely on the server config (exposed by the web UI through a javascript object) to know what to do about authentication. So they have no knowledge of your nginx proxy, its own basic auth, and even worse, about the credentials that you gave to the browser for basic auth.

I'm thinking about it, but I have to admit I don't actually have any idea for fixing that atm.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18726

**Comment by mpl** [comment]
@khimaros can you please let me know if the above CL works for you, in the Share case? if yes, I'll fix the Map (and others, if any) similarly.

**Comment by mpl** [comment]
@khimaros alright, I've applied the fix to every relevant place I could find. Please let me now if everything looks fixed for you (same CL).

**Comment by khimaros** [comment]
Everything I've tried works! If I find others, I'll open a separate bug.
