### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by invariant** [perkeep/perkeep#1227]
Freshly downloaded as per [installation instructions](https://perkeep.org/download). My go version is go1.11.1 darwin/amd64. On running `go run make.go` I get the following error:

````
gopherjs for perkeep.org/app/publisher/js error: exit status 1, ../../../../../usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:673:60: cannot use t (variable of type *rtype) as *funcType value in argument to funcLayout
../../../../../usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:336:21: cannot use methodReceiver(op, v, int(v.flag) >> flagMethodShift) (value of type *rtype) as *funcType value in assignment
exit status 1

**Comment by dmitshur** [comment]
Go 1.11.1 made a few changes to `reflect` package. It looks like GopherJS might need to be updated accordingly. I'll investigate this later today.

**Comment by mpl** [comment]
@dmitshur Jsyk, we still indeed vendor things, but we also support Go modules now.

Anyway, I'll try to bump our gopherjs dep this week-end if nobody has gotten around to it before.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18786

**Comment by mpl** [comment]
@dmitshur PTAL
