### ISSUE TITLE
all: fully deprecate dep, in favor of Go modules

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1231]
We need to:

-drop the dep related files
-update the docs to reflect that we now use Go modules instead of dep
-clean up the mess that currently shows up when one tries to update the vendor/ dir with 'go mod vendor'.

**Comment by salman-bhai** [comment]
Hi, anything here that has not been done and I can help with ?

**Comment by aviau** [comment]
Pretty sure this is complete.
