### ISSUE TITLE
Access denied when downloading synology package file

### ISSUE THREAD

**Issue by xyb** [perkeep/perkeep#1238]
I got 403 error when downloading [synology package files](https://github.com/perkeep/perkeep/blob/62ec6f94b0fc1ecb03da688d545a5169c81b0b7c/doc/synology.md). I would be grateful if anyone could fix file's permission issue and upgrade to latest version. Thank you!

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17746 now merged.

**Comment by xyb** [comment]
@mpl download and install successfully, thank you!
