### ISSUE TITLE
The donations URL on perkeep.org is invalid

### ISSUE THREAD

**Issue by JayCuthrell** [perkeep/perkeep#1241]
The [current donations URL](https://www.coinbase.com/checkouts/cb36d0d49984c31062332af51f0346a8) on perkeep.org website is invalid due to deprecated format. Coinbase donations are via newer [commerce.coinbase.com methods](https://commerce.coinbase.com/docs/#payment-buttons).

The updated donations URL on perkeep.org website would need to be of the form:

`https://commerce.coinbase.com/checkout/[unique id]`

**Comment by willnorris** [comment]
donation links removed in 0683145d61
