### ISSUE TITLE
rollsum: use go4 rollsum package instead

### ISSUE THREAD

**Issue by josharian** [perkeep/perkeep#1249]
I went to use the rollsum package again, and was sad to find that it had been made internal. It's a useful utility package. Can I convince you to make it public for the greater good? Or maybe even move it to go4 or some standalone home?

**Comment by josharian** [comment]
I'd be happy to contribute some godoc comments as a thank you. :)

**Comment by mpl** [comment]
Are you saying you already had other packages or programs that were depending on pkg/rollsum before we moved it to internal?
If yes, it seems indeed fair enough to me to move rollsum to go4.org. Although we'd have to make sure it's really Perkeep agnostic first (which I'm not certain of, and haven't checked yet).

**Comment by josharian** [comment]
Yes, I had an existing dependency before the move to internal. (It actually dates from the camlistore days.)

I believe rollsum is entirely perkeep-independent.

**Comment by mpl** [comment]
well I have no objection to it. Maybe Brad will. But in the meantime, do you wanna start by sending a PR to go4.org, that adds the current version of internal/rollsum there?

**Comment by josharian** [comment]
With pleasure. Will do next time I am at a computer.

**Comment by bradfitz** [comment]
Putting it in go4.org is fine. I just don't want it in perkeep's public API.

**Comment by josharian** [comment]
https://github.com/go4org/go4/pull/41

**Comment by josharian** [comment]
The PR has been merged. Let's re-purpose this issue for migrating perkeep to the go4 rollsum. I went to do that just now but found that I was going to have to learn a bit about `dep` to do it, plus a bunch of the tests are currently failing for me...so I was hoping that I could leave this last bit to you, @mpl.

**Comment by mpl** [comment]
@josharian 

1) I think you can forget about dep if you want, as we're supposed to drop it. Just make sure things are good with GO111MODULE=on (so go.mod), and without it (i.e. that things are correct in the vendor dir).

2) about the tests, if they're failing _without_ your change then please open a separate issue about it. If then only happen with your change then we can discuss/fix them together here or directly in the CL.

**Comment by josharian** [comment]
A bunch of the tests fail when not using Go 1.10, so I'm not quite sure how to then also test with Go modules, which hadn't been introduced by 1.10.

The test failures are without my change. I'll file a separate issue about them.

**Comment by josharian** [comment]
Sent PR #1253 that migrates to using go4.org. It doesn't include any dep or go.mod or other dependency manager changes; my apologies.

**Comment by mpl** [comment]
Yeah I saw the issues you opened, thanks. You can indeed ignore them for now I think. We/I will take care of them later.
Do not worry about Go 1.10 either. Things are are only supposed to build with Go 1.11. But it's interesting to know if you're saying we have things only broken with Go 1.11.

**Comment by bradfitz** [comment]
Done in 2a85cb7142e6af5439d6d9cf2f6ddada04b4797e
