### ISSUE TITLE
rollsum: add SplitFunc

### ISSUE THREAD

**Issue by josharian** [perkeep/perkeep#1250]
I wrote a bufio.SplitFunc that does rollsum-based tokenization. It makes rollsum splitting easy to do.

If you make rollsum public again (#1249), I'd like to contribute it, along with an example of its use. Because of the somewhat bizarre bufio.SplitFunc API, it's not as easy to write as it should be.

**Comment by josharian** [comment]
I'll close this; there is an outstanding PR at go4.org, which will either be merged or not.

**Comment by mpl** [comment]
oh I had missed that one. will review, thanks.
