### ISSUE TITLE
pkg/client: no compile time Get or Put methods that mirror semantics of pk-get and pk-put

### ISSUE THREAD

**Issue by atecce** [perkeep/perkeep#1254]
while looking for a programmatic interface to `perkeep` for a scraper of mine, i noticed there wasn't a one-to-one relationship between the contract of the `cmd` and the contract of the `client`.

should i just be using [`client.Fetch`](https://godoc.org/perkeep.org/pkg/client#Client.Fetch) for `get`s and [`client.Upload`](https://godoc.org/perkeep.org/pkg/client#Client.Upload) for `put`s? i really want to avoid invoking the `cmd` from the shell each time and forking off a child process for each `put`

what i'm really looking for is some way to do something like this

```
httpRes, _ := http.Get(url)

pkRes, _ := pk.Put(httpRes.Body)
```

**Comment by atecce** [comment]
ping :D

**Comment by tgulacsi** [comment]
Absolutely agree. I've created github.com/tgulacsi/camutil/camproxy but it's not ideal.

**Comment by atecce** [comment]
oh tyvm! will check it out

**Comment by atecce** [comment]
@mpl @bradfitz any official comment on this?

**Comment by atecce** [comment]
@mpl @bradfitz hey i’m going through old issues i’ve opened and will probably close this tomorrow. thought i’d bump it one more time

**Comment by tgulacsi** [comment]
@atecce see what https://pkg.go.dev/github.com/tgulacsi/camproxy/camutil?tab=doc Uploader/Downloader does.

**Comment by atecce** [comment]
ohhhhhhh awesome. tyvm again i guess we'll just say it's supported elsewhere!
