### ISSUE TITLE
Logo redesign proposal

### ISSUE THREAD

**Issue by IfeanyiEkperi** [perkeep/perkeep#1281]
I'll love to contribute to this project by offering a logo redesign for the project that meets all required standard while still following same theme of the already in use logo.

Logos have no minimalistic and Perkeep deserve something minimal and sleek too.

Hope I am given the chance to rebrand Perkeep.

**Comment by willnorris** [comment]
I don't think the project owners are interested in a rebrand.  We actually [just rolled out the current brand](https://twitter.com/PerkeepOrg/status/948296729526353920) last year, and I think folks are pretty happy with it.

**Comment by IfeanyiEkperi** [comment]
Okay. Thanks
