### ISSUE TITLE
How to compile without internet access?

### ISSUE THREAD

**Issue by djmattyg007** [perkeep/perkeep#1286]
I'm regularly in a situation where I'm working without internet access. Unfortunately it seems that running `go run make.go` in this situation doesn't work because it still wants to contact a remote server. I've already compiled the code beforehand with internet access, so I already have all of the dependencies available locally. Is there a way to make this work?

**Comment by bradfitz** [comment]
I'm guessing `--embed_static=false` and/or `--skip_gopherjs=true` might help?

But it really shouldn't be required.

/cc @mpl

**Comment by mpl** [comment]
Unfortunately that wouldn't be enough, as we still check whether the resources we have on disk (app/publisher/publisher.js , and server/perkeepd/ui/goui.js), are legit by matching them against the hashes that are (systematically) fetched at https://storage.googleapis.com/perkeep-release/gopherjs/publisher.js.sha256 and https://storage.googleapis.com/perkeep-release/gopherjs/goui.js.sha256

That's easily hackable though: once you are sure you have publisher.js and goui.js on disk, just add a 

```
  return nil
```

at the beginning of

```
  func fetchAllJS(doWebUI, doPublisher bool) error {
```

and things should work offline (with the flags Brad already specified).

**Comment by bradfitz** [comment]
Let's add a new flag to do all this.

**Comment by mpl** [comment]
Yeah. And reading that code, I realized there's once more warts that I
meant to remove but that are still there.

**Comment by mpl** [comment]
> Let's add a new flag to do all this.

done, PTAL.
