### ISSUE TITLE
publisher: error displaying files in sha224 parents

### ISSUE THREAD

**Issue by tajtiattila** [perkeep/perkeep#1292]
When a published container uses a sha224 hash, its page with thumbnails is displayed in publisher correctly, but file links don't work because of the hardcoded "sha1-" prefix in the call of getFullRef in newFileItemContainer of app/publisher/js/file.go.

**Comment by mpl** [comment]
@tajtiattila thanks. do you want to have a go at fixing it?

**Comment by tajtiattila** [comment]
@mpl This seems fairly trivial to fix, so I modified getFullRef and its call site in app/publisher/js/file.go to use a logical constraint with both ssh224 and ssh1 in the prefix.

Unfortunately, I'm on Windows and I couldn't get it to build the Web UI yet. Maybe we should have a Dockerfile to do just that.

**Comment by mpl** [comment]
I've updated with your fix the generated publisher.js that we host , for when one wants to run make.go without regenerating the webUI. It seems there's some caching shenanigans going on at the moment though. I'll recheck tomorrow.
