### ISSUE TITLE
Documentation on storing files encrypted

### ISSUE THREAD

**Issue by jonaswre** [perkeep/perkeep#1297]
Hi, 
i can*t find any dokumentation on storing files encrypted. Can somebody provide any information?

**Comment by followsound** [comment]
I'm also getting the following error with encryption

```
Caught panic installer handlers: error instantiating storage for prefix "/bs/", type "blobpacked": largeBlobs at "/enc-packed/" of type *encrypt.storage doesn't support fetching sub-ranges of bl
obs                            
```

**Comment by aviau** [comment]
Hello, we have recently added a little bit of documentation for the encrypt storage, let me know if that helps:
 - https://perkeep.org/pkg/blobserver/encrypt/
