### ISSUE TITLE
Perkeep uploader not working on Android 10

### ISSUE THREAD

**Issue by giganteous** [perkeep/perkeep#1300]
I'd like to raise some awareness that the uploader fails to run on android 10. It does not offer an option to upgrade in the play store.

**Comment by mpl** [comment]
@giganteous fwiw, it still works for me on a pixel 2, running Android 10 as well. So your problem is probably not just related to Android 10.
Are you saying the same installed app on the same phone, but with a previous version of Android, used to work for you?

**Comment by giganteous** [comment]
sorry, I was far too quick to react let ke this.

The error is easy to misinterpret. I attached the error.

thanks,
