### ISSUE TITLE
Add TODOs Badge to Readme

### ISSUE THREAD

**Issue by patrickdevivo** [perkeep/perkeep#1301]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/perkeep/perkeep)](https://www.tickgit.com/browse?repo=github.com/perkeep/perkeep)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/src-d/go-git)](https://www.tickgit.com/browse?repo=github.com/perkeep/perkeep)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by willnorris** [comment]
surfacing latent work isn't really perkeep's biggest problem right now.  Once some more basic triage has been done, this might be helpful, but probably not right now.  Thanks, though.  Looks like a neat service.
