### ISSUE TITLE
Perkeep on Raspberry Pi 3

### ISSUE THREAD

**Issue by GTP95** [perkeep/perkeep#1313]
Hello everyone,

I'm interested in this project and wanted to test it on a Raspberry Pi 3. Since there aren't binary packages for ARM, I resorted to compiling it from source, but I run in the following issues:
- The master branch compiles and starts fine, but crashes after a while when trying to upload two video files filling the terminal with errors about goroutines.
- The staging branch refuses to compile with an error about version length that I don't remember well
- The releases/0.10 branch, which is the one I'm mostly interested in since at the moment is the latest stable release (although I saw that in issue #1307 that you're thinking about a new stable release), compiles and starts fine, but when I log in I only see a blank page and in the terminal it trows errors about being unable to load resource files (mostly CSS files). 

I can't post here the exact errors right now because I decided to try again with master before writing and compiling different versions involves changing the version of go as well, but if you need it I can post them here in the next days. 
What should I do to be able to compile and run Perkeep on my Raspberry Pi? 
I saw that somebody else had issues running it on a Raspberry Pi 3, but that issue involved Docker and I would prefer running it natively. Thanks for your help

**Comment by GTP95** [comment]
Quick update: I tried uploading two small files, one at a time, using the master version. It seems to have worked, so maybe the crash was due to the small RAM of the Raspberry? 
But now I'm unable to see the two files using the web UI. One of them is called "arte_moderna.txt" but the search query  "filename:arte_moderna.txt" returns no file, the other is a png image, but "is:image" returns no result.

**Comment by cliveb** [comment]
@GTP95 I was thinking of trying to build Perkeep on Pi 4. Did you solve the out of RAM on Pi 3 issue?

**Comment by zenhack** [comment]
How much ram do you have, and how much data are you storing? I wonder if you're running afoul of #1271

**Comment by cliveb** [comment]
8GB. Any chance you have a stable Perkeep build for Pi? (Amazon van just delivered shiny new Pi 4)

**Comment by zenhack** [comment]
Sadly, no -- my boxes are all x86.

**Comment by cliveb** [comment]
Ok, I will try to see what I can build. Thanks for #1271

**Comment by GTP95** [comment]
> @GTP95 I was thinking of trying to build Perkeep for Pi 4. Did you solve the out of RAM on Pi 3 issue?

No, for now I'm just storing smaller files like photos, I may try again with the two videos, maybe uploading one at the time and with increased swap storage could help.

**Comment by GTP95** [comment]
> Ok, I will try to see what I can build. Thanks for #1271 

If you have any problems with the build I can send you my binaries compiled on my PI 3

**Comment by GTP95** [comment]
I've tried one video at a time and with more swap space. This time perkeep didn't crash, but I'm unsure if it really uploaded the videos, since I'm unable to find them.
