### ISSUE TITLE
Search query "attr:format:txt" doesn't return results while I have at least one txt file

### ISSUE THREAD

**Issue by GTP95** [perkeep/perkeep#1314]
Search query "attr:format:txt" doesn't return results while I have at least one txt file, and the web UI shows it in the home page and even correctly identifies it as a document. 
This is the content of the file:
```
tre più quattordici é quattro più tredici
tre più quattordici é tredici più quattro
quattro più tredici é tre più quattordici
quattro più tredici é quattordici più tre
tredici più quattro é tre più quattordici
tredici più quattro é quattordici più tre
quattordici più tre é quattro più tredici
quattordici più tre é tredici più quattro
```
The permanode has only the attribute camliContent with value sha224-88cd3c20c9541121f135e8ff7f7bc6ee50e015d38d52e3d0d2b6c7fb
and in the blob page I get the following info:

`Blob content
{
  "camliVersion": 1,
  "camliType": "permanode",
  "random": "0.29951888814467",
  "camliSigner": "sha224-7111a2e84367fdde66273a6a7bacb03756209a02c0604af2b85f7941",
  "camliSig": "wsBcBAABCAAQBQKIbgkACRCydNgEwHnRhQAA/KoIAJnz2Fx083+FIU7QVw2dfImQC769dqpkVl66F3+v28jR6raZxZKdtpN1vrC0dOQ3u4Ivad3D/ScS440ba2TUlm7RkPIXNKtOnFnMfdYKzz/XEoKaIpCrSuj5beEnMnhEQEq31NSduN9OBXKWDBaHosNSCSuvikCHw9goyB1g+s3S5TpvCGBUZ5bqiSov4Cu+nKzxhruBRxR5ZrXITNd/JAt5yi7iAugUvSAesrcZrCliB9d6NZ9KjrzuFEdk10i3JtlASTF+R0sry6ezTukXzJHXFXVCT5iEnyoNQp5Jyw4v1kCwLW0Yxm6NzkU9fKkU/hWka0VCXBSyYTmH0QuyuMA==uT82"
}

Indexer metadata

{
  "blobRef": "sha224-a9c10c697535cafea997d5d77569df583d359c93ca4953f1dec9c573",
  "camliType": "permanode",
  "size": 564,
  "permanode": {
    "attr": {
      "camliContent": [
        "sha224-88cd3c20c9541121f135e8ff7f7bc6ee50e015d38d52e3d0d2b6c7fb"
      ]
    },
    "modtime": "2020-07-09T19:50:06Z"
  }
}

Mutation claims

{
  "claims": [
    {
      "blobref": "sha224-8a43eaf785f0175907c2fadb0e3a811b8e01f996afd90807e74d9de1",
      "signer": "sha224-7111a2e84367fdde66273a6a7bacb03756209a02c0604af2b85f7941",
      "permanode": "sha224-a9c10c697535cafea997d5d77569df583d359c93ca4953f1dec9c573",
      "date": "2020-07-09T19:50:06Z",
      "type": "set-attribute",
      "attr": "camliContent",
      "value": "sha224-88cd3c20c9541121f135e8ff7f7bc6ee50e015d38d52e3d0d2b6c7fb"
    }
  ]
}

Referenced by
No references
`

**Comment by zenhack** [comment]
Try the query "format:text/plain" (with no attr: prefix).

**Comment by GTP95** [comment]
This works, thanks!

**Comment by zenhack** [comment]
No problem!
