### ISSUE TITLE
Sharing multiple files

### ISSUE THREAD

**Issue by GTP95** [perkeep/perkeep#1315]
Hello everyone.
I'm playing with Perkeep these days and now I was trying to share files, in particular photos. If I try to share single files everything works fine, then I tried to share multiple files at once with only a single link. To do this, I first created a new set with some images, then I generated the share link. The problem is that when I open the link instead of seeing the images that I intended to share I saw a page with this:
```
{"camliVersion": 1,
  "authType": "haveref",
  "camliSigner": "sha224-7111a2e84367fdde66273a6a7bacb03756209a02c0604af2b85f7941",
  "camliType": "claim",
  "claimDate": "2020-07-10T22:08:44.825Z",
  "claimType": "share",
  "target": "sha224-51004b2069820969b06d9350322ced726649b4cffa6be7381fa55d61",
  "transitive": true
,"camliSig":"wsBcBAABCAAQBQKIbgkACRCydNgEwHnRhQAAiQwIADVZPbDMJBLNva88KVDIi4RBNQMK7wGUj3hkS0zzzflphN/uiXGQZaWkPwBiNTIYFKhXItgMBZr5V++WAy/l6XRyH2xD9lpBVLfdKLUkoF008V51yY0AA50cJgd3iR1NrTpcziLoKYQteCL/eXLjoOz5UrH7pzMC6N+Zb5HTk0uzxmeaT4ZD6qZR7HzGlowkVCws8cY5MIF7SHvyjteWrVKo5UbwaDO5ALdnYAh0o1RHVu5Bg0wBNyPU+/Q0QJvfShwOsVs7RP6rkIoILPP+L722uk/zwXgRHWBNAXxIgUs/ycoibFpwhCzImknzFxmXzTNN301gMAuJRl8JTecXhgk==wLK3"}
```
In my understanding, this is the representation of a set as an object, is there a way to share multiple files with only one link or it has to be implemented yet?

**Comment by kalidor** [comment]
The generated link can be use by a friend of yours by using pk-get command line:
```
$ pk-get -shared <GENERATED URL> -o directory
```
Create the directory first, just in case.

**Comment by GTP95** [comment]
Thank you for the answer, however I'm currently using NextCloud for my file sharing needs. Maybe I'll reconsider this project in the future
