### ISSUE TITLE
permanode signatures aren't verified

### ISSUE THREAD

**Issue by usedbytes** [perkeep/perkeep#1328]
This feels like an "I must be missing something" thing, but it looks like permanode signatures aren't verified anywhere.

**Issue:**
permanodes with invalid signatures aren't caught by the indexer (or anything else?)

**Expected:**
A permanode blob with an invalid signature is caught and flagged, probably causing the server to abort.

**What happened:**
Nothing bad, the server continued as normal.

**Detail:**
I couldn't find it in the code, so I did some testing. I modified a permanode by just changing its `claimDate` to 1970-01-02 instead of 1970-01-01, without changing the `camliSig` value. Then manually put it back in the blob store with the correct sha224 digest, and restarted the server with forced re-indexing.

I expected the server to complain about a signature check failure, but nothing bad happened. I did the same process for a "claim", and it _did_ fail as expected during reindexing.

Here's my modified blob (`sha224-71cce1c5e5abc3cffd2a5bdea60d9dd459be959507a1a9997ed09c19.dat`):
```
{"camliVersion": 1,
  "camliSigner": "sha224-adb50de44b6643ade466293ea16ed0309b852a6d229fb4c69d70d1ab",
  "camliType": "permanode",
  "claimDate": "1970-01-02T00:00:00Z",
  "key": "sha224-9c0f2b9acd191ce28c07bc51cdab210b3271425566b387b6c045fed5"
,"camliSig":"wsBcBAABCAAQBQIAAAAACRBUNwPP1Pmb4gAAmVkIAHPEeUG8kxaK8J/AT1xB7+B+WnuYCAo1lyzt/UT3gb+s8fNxi8HBX3fyku+D7LyryuwEHLYzlzbH4/VSdcUb3JYi3nG8YweiWbReBLRqH8JHwuW4HtpIfVxeH30xY0ACRJRbLFCQGLN8y5mfbYPzbg4KGnbhzXjynweVS9lnVsy/6ks5V/AIC+ZSLEd18bjyEWkKAfoHSQu5VPbEQGND5ci2joU8LIHEDcKDBIE0XbQAPIwv1eojvFHf3jTaIYzGGTlQJyfAcP09KH4yqc2LUZHMbZYL+AiLteLhGawwnTHLhDm1Nk3SoIbxKN9PNlBAd62Pl7JLwm7xuQkR6q2Y0EB==/CIx"}
```

If I directly ask the `verifyHandler` to verify it, then it fails:
```
$ curl --data-urlencode "sjson@sha224-71cce1c5e5abc3cffd2a5bdea60d9dd459be959507a1a9997ed09c19.dat" \
http://localhost:3200/sighelper/camli/sig/verify
{
  "signatureValid": false,
  "errorMessage": "signature verification failed"
}
```
But `perkeepd` starts and re-indexes just fine. I confirmed that the blob is actually getting indexed with `CAMLI_DEBUG=1`

Maybe this is "expected", but I'd say it's quite surprising - if the signature isn't checked or used for anything, then why are permanodes signed at all?

**Comment by aviau** [comment]
Thanks for the good bug report!

It turns out that the indexer does not verify signatures on permanodes, it only verifies signatures on claims modifying the permanode.

I have just submitted a patch.

Cheers,
