### ISSUE TITLE
Support a free geocoding service

### ISSUE THREAD

**Issue by lenormf** [perkeep/perkeep#1342]
Hi,

I see that Google geocoding support is available, however this is a paid service and I only have a minimal amount of coordinates to resolve.

Would it be possible to support other geocoding services that don't charge for 0-X.000 queries? For example[Yandex.Maps](https://yandex.com/dev/maps/geocoder/)? If it's already possible, how to configure it?

Thanks!

**Comment by jacobwhall** [comment]
OSM also has a [geocoding api](https://wiki.openstreetmap.org/wiki/Nominatim) that might be of interest.
