### ISSUE TITLE
pk-put init --gpgkey does not accept fingerprint

### ISSUE THREAD

**Issue by singpolyma** [perkeep/perkeep#1361]
Only works with short keyid.

Also, the error when you run init with no switches tells you there is a switch `--secret-keyring` ... there is not.  `CAMLI_SECRET_RING` env var works, though.

**Comment by aviau** [comment]
You used a long fingerpring with the 0x prefix?

**Comment by aviau** [comment]
> Also, the error when you run init with no switches tells you there is a switch --secret-keyring ... there is not.

This flag should be placed before `init`, but its there.

**Comment by singpolyma** [comment]
>You used a long fingerpring with the 0x prefix?

No 0x

**Comment by aviau** [comment]
can you provide the exact command?
