### ISSUE TITLE
`goui.js` breaking the dependency scanner on upgrade

### ISSUE THREAD

**Issue by rjp** [perkeep/perkeep#1384]
Pulled to `commit a49f6851` this morning, rebuilt the server, and ran into this.

```
Mar 01 12:53:40 archlinux perkeepd[2549427]: 2021/03/01 12:53:40 Could not parse deps for goui.js: bufio.Scanner: token too long
```

Seems to be because I have an old version (maybe a year since my last pull?) of `server/perkeepd/ui/zembed_goui.js.go` lying around which doesn't seem to get cleaned up at any point when pulling new versions (or at least deleting that file and rebuilding made everything work again.)

**Comment by tdilo** [comment]
Coincidentally, I ran into the same issue yesterday (upgrading from 0.11).The web UI did not load properly and it produced some errors in the browser's developer console. After running `git clean -fdx` and rebuilding, the web UI worked again.

I am uncertain whether we can expect to produce a working build from an unclean source tree of unknown age. Switching resource embedding to the new standard library's `embed` package might resolve this particular issue as a side effect.

**Comment by aviau** [comment]
We can probaly clean that file in make.go to avoid issues like this. Assigning myself.
