### ISSUE TITLE
Update minimum version to go1.16

### ISSUE THREAD

**Issue by contrast-jproberts** [perkeep/perkeep#1398]
https://github.com/perkeep/perkeep/commit/ccad6635e4487695851fe15b50df83df4b76493c introduced the `go:embed` directive and the `embed` and `io/fs` packages into the main branch. Both of these features require Go 1.16 to build. However, the documentation still claims that perkeep only requires Go 1.15. A quick search for 1.15 in the repo showed the following cases that likely need to be upgraded. I'm not very familiar with the codebase though, so there may be more.

1. `BUILDING:3` -- should read "Install Go 1.16 or later"
2. `Dockerfile:25` `ENV GOLANG_VERSION 1.15.7` -- this probably needs to be updated to 1.16, not sure what minor version
3. `misc/docker/go/Dockerfile:10` `ENV GOLANG_VERSION 1.15.3` -- not sure how this is used, might need to be updated
4. `website/content/download.md:17` -- should read `Perkeep requires [Go 1.16 or newer](https://golang.org/dl)`

cc @aviau

**Comment by aviau** [comment]
Thanks, fixed.

We shouldn't hardcode the specific go version at so many places, but I didn't want to get into that right now.
