### ISSUE TITLE
virus inside https://perkeep.org/dl/perkeep-0.11-linux.tar.gz

### ISSUE THREAD

**Issue by swloopit** [perkeep/perkeep#1569]
uploading the file to virustotal  https://perkeep.org/dl/perkeep-0.11-linux.tar.gz
i see this result
https://www.virustotal.com/gui/file/b3fc257a3831e7782dd76731f286d3e914c2aac37a198eee7c7f076909eb6fb9
you can verify?

**Comment by Mohammed90** [comment]
Pretty sure that's false-positive. There's an issue with AV heuristics and Go binaries.

**Comment by swloopit** [comment]
> Pretty sure that's false-positive. There's an issue with AV heuristics and Go binaries.

I
