### ISSUE TITLE
Importer base URL wrong for remote host

### ISSUE THREAD

**Issue by ajmeese7** [perkeep/perkeep#1570]
I am running Perkeep on my Raspberry Pi, which is configured for remote access via its IP address. The Pi can either be accessed at `http://192.168.1.168` or `http://raspberrypi" from my Windows machine, because the IP links to the Pi's `localhost`.

When trying to access items from the 'Importers' page, the URLs look like `http://localhost:3179/importer/instapaper` instead of `http://raspberrypi:3179/importer/instapaper`. I was hoping the project could be reconfigured to use the actual URL of the page rather than assuming localhost, I looked into fixing the issue myself but I am very unfamiliar with Go so I was unable to do so. Of course I can manually go into the browser bar and fix the URL, but it would be a lot nicer if the project would handle my use case automatically.

Any help would be appreciated, thanks!

**Comment by tgulacsi** [comment]
Set "baseURL": "http://raspberrypi:3179" in
.config/perkeep/server-config.json

Tamás Gulácsi

**Comment by ajmeese7** [comment]
Worked like a charm, thanks for your help! Closing out now :)
