### ISSUE TITLE
how to configure replication, user credentials

### ISSUE THREAD

**Issue by diresi** [perkeep/perkeep#1576]
Hi!

So I started with building the daemon and running it, did some `pk put init` and `pk put file <dir>` and can even get it back, which is awesome :)
Then I wanted to replicate things to another machine, started the daemon there and hit the docs at https://perkeep.org/doc/server-config#replication ... but then failed to grasp them.

I think it's really about two main questions:
1. My configs don't have any `/bs/` config entry, although they're reported in the Web UI of course, so I guess those are built in defaults. But then again, where do I put the `/bsrepl/` block exactly?
2. Accessing non-local machines require some form of authentication, and it seems that `username:user:pass` maps to HTTP basic auth. I'm not running behind some reverse proxy but access the perkeep server process/port directly. Soooo ... how do I configure authentication?

I feel like those questions are so basic that I must've missed something in the docs, although I read them more than once, I swear! :grinning:

Would you please give me a nudge or two to push me into the right direction?

**Comment by haorenfsa** [comment]
Hi, I used to run into the same problem. The doc doesn't state clearly, in fact you can found a full configuration in the web page when perkeepd is running, the url is : http://localhost:3179/debug/config

**Comment by diresi** [comment]
Hi @haorenfsa, thanks a lot for your comment!
I'm afraid I lost interest already, so I probably won't be giving feedback :/ Sorry!

FWIW I'm gonna close the issue to not bugger the maintainers more than necessary.
