### ISSUE TITLE
blob upload with http api can't attach metadata

### ISSUE THREAD

**Issue by fujohnwang** [perkeep/perkeep#1577]
https://perkeep.org/doc/protocol/blob-upload

with current blob upload protocol, I can't achieve same goal like what `pk-put --filenodes` does.

Only uploading successfully doesn't make the blob/file display in the web UI.

**Comment by MichaHoffmann** [comment]
For the blob to show in the web UI it needs to be a [permanode](https://perkeep.org/doc/schema/permanode) that has a `camliContent` attribute whose value is the blob you uploaded. So you would need to upload 3 blobs: 1 blob, 1 permanode and one claim that sets this attribute on the permanode.

**Comment by fujohnwang** [comment]
> 

got it, many thanks 👍
