### ISSUE TITLE
android-app: link to playstore is dead 

### ISSUE THREAD

**Issue by MichaHoffmann** [perkeep/perkeep#1582]
The link to the google play store seems to be dead, is the android app still alive?

**Comment by bradfitz** [comment]
Google regularly changes the Play Store rules and requires certain changes which if you don't do, they remove your app.

I guess they altered the deal.

**Comment by MichaHoffmann** [comment]
Hey @bradfitz,

Thanks for your answer! Is there a plan to get it back into the playstore? Or should it be installed through other means?
