### ISSUE TITLE
Can't upload file via web ui with server on Windows

### ISSUE THREAD

**Issue by ABCRic** [perkeep/perkeep#1587]
### Repro steps
* clone repo and `go run make.go`
* run perkeep
* try to upload a file via the web ui
* stuck at "Uploaded 0 (0%)"

### Additional info
* App is running on Windows 10. Trying the same steps on a Debian box behaved as expected.
* The Firefox dev console shows this error:
> Loading Worker from “http://localhost:3179/ui/hash_worker.js?r=1643067598268” was blocked because of a disallowed MIME type (“text/plain”)
* The Chrome dev console shows this error:
> Refused to execute script from 'http://localhost:3179/ui/closure/goog/bootstrap/webworkers.js' because its MIME type ('text/plain') is not executable.
>   (anonymous) @ hash_worker.js?r=1643067695589:19

Probably related: https://github.com/golang/go/issues/32350

**Comment by MichaHoffmann** [comment]
Should we add an `suffix is .js` => `application/javascript` branch here as a workaround?

https://github.com/perkeep/perkeep/blob/46e4e4f9e791a8304ff96ac71d041b30d4a031aa/pkg/server/ui.go#L521

**Comment by MichaHoffmann** [comment]
This should be fixed with #1642
