### ISSUE TITLE
Error while trying to access published set.

### ISSUE THREAD

**Issue by kalidor** [perkeep/perkeep#1591]
Hi, first of all, thanks for this awesome tools.

I'm trying to publish a set of items. The "publish" configuration seems correct, also the set I want to share, use `camliRoot` and `camliPath:FOO : sha224-...`.

However when i'm requesting the published web page, I got the title displayed, but nothing else.

In the perkeep log, I got "2022/02/22 18:29:30 Failed to open file "js.js.map" from embedded resources: open js.js.map: file does not exist".

Obviously this file don't exist on server side, the only reference to it, is in published.js generated file, last line:
```Javascript
[...]
//# sourceMappingURL=js.js.map
```

I'm not sure the fact that the file does not exist implies the web page is missing all images...

I'm using the last github commit (a42e61b826e6c8464372fc638cf14e5411452725).

**Comment by MichaHoffmann** [comment]
I tried to reproduce but it seem to work for me locally ( with devcam and a freshly installed publisher ). Can you maybe try to see if its reproducible with the dev environment too?

**Comment by kalidor** [comment]
Hm, it seems i didn't fully understand what I was trying to do... Now it's more clear.

I use the following command to add my directory containing pics:
```pk-put file -permanode --title "Barcelona 2014" --tag=barcelone,holiday 2014-barcelona/```
The results is a directory with a permanode, but pics in this directory do not have permanode.

So my question is "Is it possible to create share a permanode of a directory containing (in my case) pictures which don't have permanode associated on each pictures ?"
So far, i will say no, but can you confirm ?

Using the command `pk-put file -permanode -filenodes --title "Barcelona 2014" --tag=barcelone,holiday 2014-barcelona/`, I was able to set up the share and then access it.

**Comment by MichaHoffmann** [comment]
Hey @kalidor 

Ill try in the evening!

**Comment by kalidor** [comment]
Seems "-filenodes" is required.
I can share it and retrieve the directory using `pk-get -shared <URL><SHA-of-shared-permanode> -o <DIR>`.

However, when trying to get it using the publisher, I got a 404 not found.
If I restart perkeepd, i can access it.
If I add a new directory (2) containing pics (-filenodes) and make a permanode to share it.
If I restart perkeepd, i can access the new one(2), but not the first...

**Comment by MichaHoffmann** [comment]
No worries, your issue helped me getting to know the publisher too as i hadnt used it yet! Seems pretty cool though.
