### ISSUE TITLE
The Perkeep Android app is missing from the Google Play Store

### ISSUE THREAD

**Issue by Sitwon** [perkeep/perkeep#1596]
The download link on the website is broken. The app is missing from the store. The alternate version linked on the website appears to be an older version (even uses the older Camlistore name and branding).

**Comment by aviau** [comment]
see https://github.com/perkeep/perkeep/issues/1582

**Comment by Sitwon** [comment]
Thanks, I has assumed that was the root cause. However, the solution is still unanswered. Is Perkeep dead?

**Comment by aviau** [comment]
Dead is harsh :) But its fair to say that nobody right now is maintaining the Google Play listing.

**Comment by Sitwon** [comment]
Not maintaining the Google Play listing, nor any alternative listing. Which means the project is unavailable on Android, except to anyone who may choose to build it themselves locally. Not to mention, none of the clients aside from web have been touched in about 4 years.

For that matter, looking at the commit history that last few years are just a smattering of small bug fixes and dependency bumps. Plus one breaking change to blob storage with no transition path for existing repos.

I like the idea of Perkeep, but development seems to have stalled to the point that for an end-user it is effectively "dead". 

I've managed a number of software projects, including open source projects, through their natural decline and end of life. Judging by the activity on Github, this project is well down that path. Not that it couldn't be revived, but it does not appear there's an active effort to revive it happening. I guess, just like #1582, I may simply give up on this project.

**Comment by MichaHoffmann** [comment]
Do you have an idea what is to be done to get the android app live again? I'm not really an android developer, but would be willing to invest some time in that, since i also would like to use the app. Could use some pointers though.

**Comment by MichaHoffmann** [comment]
It seems that minimum targetSdkVersion is 30, ill try bumping that and see how that goes.

**Comment by MichaHoffmann** [comment]
After some hacking, the app now runs on phone with android 11 and sdk version 30. Not sure how to proceed though.

**Comment by Sitwon** [comment]
I don't know what the project governance looks like, but the only obstacle
to posting the APK to the Google Play Store or F-Droid would be having
permission to publish from the owner(s) of the trademark.

It may be smart to have someone with commit authority host the APK on
GitHub as a release binary along with a cryptographic signature, if trust
is a concern.

**Comment by MichaHoffmann** [comment]
After some further hacking it now also runs on android 12 with sdk version 32. ( my wifes phone ). Ill create a PR in a bit.

**Comment by aviau** [comment]
I can test/review/merge PRs.

If F-Droid can pull builds from github release that would be great. Then we can just setup a github workflow to build and release the APK.

**Comment by MichaHoffmann** [comment]
I created a PR with my changes. I made the mistake of including a bunch of Android Studio refactoring suggestions which makes this harder than necessary to review i suppose.

**Comment by MichaHoffmann** [comment]
its back: https://play.google.com/store/apps/details?id=org.camlistore

i just installed and verified that it works on my pixel 5

**Comment by tgulacsi** [comment]
It quits on "Upload All".
How can I debug it?

The "Version" produces the following error:
![photo1648668882](https://user-images.githubusercontent.com/256074/160916938-8aae92dc-70d2-4972-aa0c-b7edc82b4165.jpeg)

**Comment by MichaHoffmann** [comment]
> It quits on "Upload All". How can I debug it?

Hey, it seems that the `pk-put` binary is not where it's expected on your machine. Which version of Android are you using?

**Comment by aviau** [comment]
> It quits on "Upload All".

Not the same issue as OP, can you please open one instead of having a single issue for all android things?

**Comment by MichaHoffmann** [comment]
> It quits on "Upload All". How can I debug it?

Was able to reproduce this in android studio in the VM with Google Pixel 5 with API level 32 even though the application exists on the phone. I found this in the changelog:
```
Non-NDK native shared libraries are now only accessible when they are explicitly requested.
```
This maybe blocks us from executing the embedded `pk-put` binary

**Comment by MichaHoffmann** [comment]
Hey @tgulacsi,

can you try to reinstall the app? I was able to reproduce your issue with a fresh install from google play ( i had a debug build previously ), tried to fix it ( it was releated to the 64bit abi i think), published a new release and now it works with a fresh install from google play on my phone again.

**Comment by tgulacsi** [comment]
Yup, the last update works, thank you!

**Comment by MichaHoffmann** [comment]
> Yup, the last update works, thank you!

Thats pretty cool!
