### ISSUE TITLE
openpgp: invalid data: tag byte does not have MSB set

### ISSUE THREAD

**Issue by Huangsh17** [perkeep/perkeep#1601]
2022/04/03 11:15:42 bad request: jsonsign: openpgp.ReadKeyRing of "/Users/hsh/.config/perkeep/identity-secring.gpg": openpgp: invalid data: tag byte does not have MSB set

**Comment by MichaHoffmann** [comment]
Could be related to https://github.com/golang/go/issues/29082. `https://pkg.go.dev/golang.org/x/crypto/openpgp` is deprecated. The issue links to a workaround i have not verified: https://gist.github.com/stuart-warren/93750a142d3de4e8fdd2?permalink_comment_id=3131683#gistcomment-3131683.

**Comment by featherbutt** [comment]
A couple observations:

- Despite the autogenerated key being stored in a file called "identity-secring.gpg", the key file is actually an Armored ASCII formatted (.asc) key.
- According golang/go#29082, the function ReadArmoredKeyRing is needed to read keys in the .asc file format.
- It looks like https://github.com/perkeep/perkeep/commit/9bc621fd16e62f45548eb6abceed6ed66e71b5c5 was intended to allow keys in either format to be used by replacing calls to openpgp.ReadKeyRing with a custom function that calls ReadArmoredKeyRing first and then calls ReadKeyRing as a fallback if the first call fails.
- However, that commit doesn't replace every call to openpgp.ReadKeyRing. For instance, there are some additional calls in [pkg](https://github.com/perkeep/perkeep/tree/master/pkg)/[jsonsign](https://github.com/perkeep/perkeep/tree/master/pkg/jsonsign)/sign.go
- I was able to workaround the issue by importing my key into Kleopatra and exporting in the GPG Binary File format (.gpg)
- I suspect that this issue can be fixed simply by finishing replacing all calls of openpgp.ReadKeyRing with jsonsign.ReadKeyRing

I'll test that tonight.
