### ISSUE TITLE
Problems upgrading from 2021-02-07-a49f685155+ to 2022-04-28-d605f86c82

### ISSUE THREAD

**Issue by rjp** [perkeep/perkeep#1609]
Ran `git pull` to update to latest master but then it would no longer build due to problems with `perkeep.org/pkg/fileembed` being missing.

In the absence of instructions on how to update to a newer version, I tried `go run make -website` as a way to refresh the autogenerated CSS/JS files but that didn't seem to touch, e.g., `clients/web/embed/fontawesome/zembed_css_font-awesome.css.go`.  Same with `go run make.go -static`.

Then I tried the brute-force approach of "delete everything mentioning fileembed" but that created its own set of build problems.

Checking out a clean version of `master` which built fine.

Maybe a note about updating ("it's probably easier to use a clean checkout than `git pull` from an old version") might be helpful?

**Comment by bradfitz** [comment]
Sorry, just noticed this issue again.

I don't recall ever having to blow away the whole directory and start over. I always just `git pull` etc from my various dev machines.

Closing, as it's impossible to debug whatever git state you were in two years later :)
