### ISSUE TITLE
Does Perkeep chunk data across nodes?

### ISSUE THREAD

**Issue by lonnietc** [perkeep/perkeep#1626]
Hello,

New to Perkeep, but it looks interesting for possible use in a project needing type of P2P redundant filesystem.

My concerns are will latency and file redundancy.

In as much, I am wondering if Perkeep chunks (splits) files across many nodes as well as to shard chunks for replication in case of node failures that could make them go offline?

What I am working on is a type of P2P online gaming system in which each local node is a P2P server that local users connect when going online. The server nodes are in P2P so that the users get any files needed from a P2P filesystem that has file chunks closest to them for lower latency.

The idea is that all game content files are shared across the P2P filesystem and are locally cached on different peers for use by other nearby peers when needed.

It seems that Perkeep "might" be a possible solution for the P2P filesystem since I would like to allow users to simply mount it as well and have it appear as a local filesystem on their Windows machine.

Any thoughts on this?
Thanks in advance

**Comment by tgulacsi** [comment]
Why not ipfs?Perkeep's client does the chunking, the server the sharding. It can be bent as you wish, just not easy.

**Comment by lonnietc** [comment]
Hello and thanks for the quick reply.

I did not want to use IPFS since it has been reported to have high latency as well as I need to run local nodes for all instances. I did look into libp2p (go-libp2p) as well as a number of other projects hoping not to need to re-invent the wheel and can use with a Golant or C++ solution for cross-platform onto Windows, Linux, and OSX, but Golang seems to be the best for this.

I was hoping to achieve low latency, as well as a system that would chunk and spread out the chunks across the P2P nodes for redundancy so that nearby nodes with some file chunks could service requests of a particular node as well as to manage and minimize the problem of having nodes join/leave the network so it would have to self-balance out the chunks to keep latency low and provide failover. (That was the idea at least)

Additionally, I wanted it to be easy in the sense that to the user perspective it would just appear as a mounted filesystem that they could "publish" their content which would be available to all of the other nodes in the P2P mesh network.

To this end, I had been searching for possible solutions and came across Perkeep, Upspin, Keybase, IPFS, and a few other home brew possible approaches that I am investigating for possible use.

**Comment by tgulacsi** [comment]
On Sun Nov 27, 2022 at 5:50 PM CET, LonnieTC wrote:
> Hello and thanks for the quick reply.
>
> I did not want to use IPFS since it has been reported to have high
> latency as well as I need to run local nodes for all instances. I did
> look into libp2p (go-libp2p) as well as a number of other projects
> hoping not to need to re-invent the wheel and can use with a Golant or
> C++ solution for cross-platform onto Windows, Linux, and OSX, but Golang
> seems to be the best for this.
>
> I was hoping to achieve low latency, as well as a system that would
> chunk and spread out the chunks across the P2P nodes for redundancy so
> that nearby nodes with some file chunks could service requests of a
> particular node as well as to manage and minimize the problem of having
> nodes join/leave the network so it would have to self-balance out the
> chunks to keep latency low and provide failover. (That was the idea at
> least)
>
> Additionally, I wanted it to be easy in the sense that to the user
> perspective it would just appear as a mounted filesystem that they could
> "publish" their content which would be available to all of the other
> nodes in the P2P mesh network.
>
> To this end, I had been searching for possible solutions and came across
> Perkeep, Upspin, Keybase, IPFS, and a few other home brew possible
> approaches that I am investigating for possible use.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/perkeep/perkeep/issues/1626#issuecomment-1328293272
> You are receiving this because you commented.
>
> Message ID: ***@***.***>

Perkeep can work with low latency, but you want to distribute the
chunks. But when the client has to get the chunks from different hosts, 
won't that be bad for latency? 
It can be beneficial, if all your hosts available and has the same
latency...

Or you can use the "blobpacked" storage that zips a file's chunks and
stores them close.

For disk space and speed, "diskpacked" is better than "localdisk",
"blobpacked" has better locality, but needs deletion, which "diskpacked"
lacks. A "blobpacked" over "localdisk" as big store, "localdisk" as
small store may be the best, but "blobpacked" leaves the small chunks
there sometimes.

Where would you put your DHT? "Under" as a blobstore, or "over" as an
app that uses perkeep for storage?

Perkeep is quite modular, but the server part is more like a monolith.
For me the easiest was to use it as a simple blob store without
indexing. I do the "index" (really just file name - blob ID mapping) in
a separate DB.


But my instinct says that 

1. you should measure first - maybe the network latencies won't be too
big for you, or they will kill all your dreams and force you to cache
everything locally, and just backup to the other hosts.

2. the hardest part here is the distributed cache, not the backend
storage. Torrent/DHT is way better for throughput than latency.

Good luck,
Tamás Gulácsi

**Comment by MichaHoffmann** [comment]
This at least doesnt feel like the usecase that perkeep was built for; so some other tool might be better suited.

**Comment by bradfitz** [comment]
Closing, as this was a question and the discussion seems over.
