### ISSUE TITLE
backgrounding pk-mount

### ISSUE THREAD

**Issue by reppard** [perkeep/perkeep#1628]
maybe i'm doing something wrong. how do you background or daemonize the `pk-mount` process?

**Comment by MichaHoffmann** [comment]
Hey, disclaimer: i dont use pk-mount day to day. Having said that, if i would need to do this i would probably set it up as a systemd unit, approximately like [this](https://gist.github.com/klutchell/70ff1de0b7f91bd13f69c0aab8c305f0).

**Comment by reppard** [comment]
> Hey, disclaimer: i dont use pk-mount day to day. Having said that, if i would need to do this i would probably set it up as a systemd unit, approximately like [this](https://gist.github.com/klutchell/70ff1de0b7f91bd13f69c0aab8c305f0).

Yeah that makes sense. I think I was thinking about it like a traditional `mount` call. Thanks for the link. Do you think creating a PID file and using that to call `kill` on it for the `ExecStop` call would be sufficient?

**Comment by MichaHoffmann** [comment]
You dont need to kill `pk mount` really you can just `fusermount -u /path/to/mount` in ExecStop i think!

**Comment by reppard** [comment]
I've got something working. No need to worry about ExecStop it seems. systemd just kills the PID in question on a stop. Thanks for the input @MichaHoffmann! I'll close this issue now.
