### ISSUE TITLE
Package documentation is broken on perkeep.org

### ISSUE THREAD

**Issue by usedbytes** [perkeep/perkeep#1658]
The links which should go to package documentation pages are all incorrect.

For example, go here: https://perkeep.org/cmd/ , all of the links are to https://perkeep.org/cmd/ , not the command docs

Go here: https://perkeep.org/pkg/ , all of the links are to https://perkeep.org/pkg/ , not the package docs

The documentation is still there if you manually enter the URL (e.g. https://perkeep.org/pkg/app ) you just can't reach it by browsing

**Comment by bradfitz** [comment]
Whoops! Thanks for the report.

**Comment by bradfitz** [comment]
Fixed.
