### ISSUE TITLE
Get rid of thumbnailSize from DescribeRequest

### ISSUE THREAD

**Issue by aboodman** [perkeep/perkeep#321]
<pre>There is no longer any need for it -- clients can get the aspect ratio from the
description of images, and then use the mh parameter to ui/thumbnail to request the
image size they want.

This will also naturally result in getting rid of the weird code in the search package
that knows about the icons the web ui likes to use for folders and files.</pre>

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5127

**Comment by mpl** [comment]
1576fdad6da43b75b54d81858829cdc007e576b0

not closing, because I haven't thought about @wathiede's question.

**Comment by mpl** [comment]
closing until it @wathiede 's question becomes relevant again.
