### ISSUE TITLE
AMI - Amazon image

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#34]
<pre>We should have an AMI image for people to run their own Camlistore instance of.

It should contain:

-- minimal Linux (Debian, Ubuntu, whatever) with barely any tools, services.

-- MySQL running locally.  for now to be lazy we can just say the whole AMI is EBS-root,
and use the same EBS volume for the OS and MySQL's state, but in the future we'll want a
tiny EBS root for the OS (like 1GB) and have MySQL on its own resizable EBS volume, but
that can come later.

-- the setup wizard (<a href="https://camlistore.org/issue/14">issue #14</a>), with basically just S3 storage support.

-- TLS: self-signed cert on boot, with the first user to hit it setting the admin
password for the UI.  option to set the cert later, from the web UI.</pre>

**Comment by willnorris** [comment]
closing this, since docker definitely turned out to be the way to go.
