### ISSUE TITLE
camget always makes a tempdir?

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#350]
<pre>Looks like camget always makes a tempdir:

$ devcam get sha1-f2b0b7da718b97ce8c31591d8ed4645c777f3ef4
2014/01/20 13:44:26 Using temp blob cache directory
/var/folders/zr/clvw_31d1wdcd404ybr3pmch0000gn/T/camlicache105937725
2014/01/20 13:44:26 Fetching sha1-f2b0b7da718b97ce8c31591d8ed4645c777f3ef4

        diskCacheFetcher, err := cacher.NewDiskCache(cl)
        if err != nil {
                log.Fatalf(&quot;Error setting up local disk cache: %v&quot;, err)
        }
        defer diskCacheFetcher.Clean()
        if *flagVerbose {
                log.Printf(&quot;Using temp blob cache directory %s&quot;, diskCacheFetcher.Root)
        }</pre>

**Comment by adamdecaf** [comment]
I'm not seeing the problem here? `diskCacheFetcher` can be used by branches in several spots down below.

https://github.com/perkeep/perkeep/blob/7a54a2c07a88a30eb0d8df63c8544c1b2d9a97c4/cmd/camget/camget.go#L126

**Comment by bradfitz** [comment]
Yeah, this seems fixed.

```
$ camget -verbose
2018/01/07 11:30:50 Using temp blob cache directory /home/bradfitz/.cache/camlistore/blobs
2018/01/07 11:30:50 HTTP requests: 0
2018/01/07 11:30:50     responses: 0 (h1), 0 (h2)
```

It's not making up random temp dirs per run.
