### ISSUE TITLE
localdisk: test filesystem on start-up

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#397]
<pre>Per thread with Brian Marete on the mailing list about FUSE NTFS-3G on Linux maybe
misbehaving, 

We should have the localdisk storage target test the filesystem on start-up.

Ala:

Write a test program:

tempDir := ...
tempFile := filepath.Join(tempdir, &quot;FILE.tmp&quot;)
filename := filepath.Join(tempdir, &quot;FILE&quot;)
err := ioutil.WriteFile(tempFile, []byte(&quot;some file contents&quot;), 0644)
...
if _, err := os.Lstat(filename); !os.IsNotExist(err) {
    panic(&quot;lies. filesystem sucks 1&quot;)
}
if err := os.Rename(tempFile, filename); err != nil {
   log.Fatal(err)
}
if fi, err := os.Lstat(filename); err != nil {
   panic(&quot;lies. filesystem sucks 2&quot;) // this is the one I fear
}</pre>

**Comment by adamdecaf** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/12930 

I noticed `.checkfs()` was called a couple extra times. Would we want this to be called each time? 

```
mkdir("/Users/adam/bad/cache/771242912\0", 0x1C0, 0x33A)		 = 0 0
mkdir("/Users/adam/bad/282128511\0", 0x1C0, 0x33A)		 = 0 0
lstat64("/Users/adam/bad/packed/084032466/FILE\0", 0xC4207F2B98, 0x200)		 = -1 Err#2
```
