### ISSUE TITLE
New environment vars are undocumented

### ISSUE THREAD

**Issue by wathiede** [perkeep/perkeep#486]
<pre>$ go run dev/envvardoc/envvardoc.go 
Undocumented                  Location
CAMLI_API_HOST                pkg/app/app.go:35
CAMLI_APP_BACKEND_URL         pkg/app/app.go:58
CAMLI_PICASA_FULL_IMPORT      pkg/importer/picasa/picasa.go:150
CAMLI_REINDEX_START           pkg/index/index.go:221
CAMLI_S3_TEST_CONFIG_JSON     pkg/blobserver/s3/s3_test.go:29
CAMLI_SERVER                  pkg/client/config.go:255
CAMLI_SYNC_VALIDATE           pkg/server/sync.go:116
CAMLI_TWITTER_FULL_IMPORT     pkg/importer/twitter/twitter.go:159
CAMLI_TWITTER_SKIP_API_IMPORT pkg/importer/twitter/twitter.go:197

It would be nice to get these added to doc/environment-vars.txt</pre>

**Comment by josephholsten** [comment]
@willnorris this could use the doc label
