### ISSUE TITLE
ui: feature flags

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#516]
<pre>Make it possible to enable conditional UI features via the config file.

This is regarding Mario Russo's email to the list:

Currently it is disabled by default - to use you must set a flag in index.js (line ~52):

cam.IndexPage = React.createClass({
    displayName: 'IndexPage',
 
    // TODO: flag to hide tagging functionality until development complete
    DEBUG_TAGS: false,  // set to true if you want to enable 

Please let me know if you notice any bugs.</pre>

**Comment by mpl** [comment]
@dotMR @aboodman Aaron, does your last comment on the CL mean that the CL is not needed anymore and that this issue can be dropped as well?

**Comment by dotMR** [comment]
After the tagging functionality was adopted into the web UI there was no longer an immediate need for the CL.

The only uses I've thought of since that time are a way to provide:
- a default query for the UI
- tag(s) that are applied by default when items are uploaded through the UI.
