### ISSUE TITLE
ui: slow & no feedback while creating a large set

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#551]
<pre>I tried to create a large set by selecting hundreds of photos and clicking the sidebar
&quot;Create set with items&quot;.

It didn't seem to do anything. There was no reaction to my click. I only later noticed
it was doing hundreds of HTTP requests (noticed in my server logs) but the UI showed no
progress.</pre>

**Comment by dotMR** [comment]
adding dialog to set creation process: https://camlistore-review.googlesource.com/#/c/4546/
