### ISSUE TITLE
Restart camlistored from the UI

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#558]
When making configuration changes such as switching to another HTTPS certificate, camlistored needs to be restarted. We should make it easy for users to do that, in particular on remote platforms such as GCE.

We already have most of the code to do that (around osutil.RestartProcess) server-side because we already handle some signals in camlistored.
So now we should add a button or some such component in the UI to be able to trigger a server restart.

**Comment by mpl** [comment]
On topic with this issue, but no need to reopen it:

I've just tested that restart works well with an instance deployed on GCE with our wizard, seems good. However, since we have an automatic restart defined in the systemd service for camlistored, isn't there a risk of the two somehow racing? Like systemd detecting (no idea how it does it) that camlistored is dead because it's taking a bit of time to restart, and then trying to start it on its own as well?
Maybe we should increase a bit the the RestartSec param in the service? Or maybe instead of restarting we do a kill when we're in the "running on gce" case (and let systemd restart camli)?

@bradfitz do you think it's worth investigating, or do you know there's no risk at all?

**Comment by bradfitz** [comment]
Instead of failing, we can just re-`exec` ourselves, then systemd never notices.

**Comment by saljam** [comment]
The restart just execs the new camlistored, which shouldn't trigger
systemd's 'process exited' logic.

Systemd does have a watchdog feature but it's disabled by default so I
don't think we should worry about that. (It involves calling sd_notify
repeatedly)


On 12 January 2015 at 21:51, mpl <notifications@github.com> wrote:

> On topic with this issue, but no need to reopen it:
>
> I've just tested that restart works well with an instance deployed on GCE
> with our wizard, seems good. However, since we have an automatic restart
> defined in the systemd service for camlistored, isn't there a risk of the
> two somehow racing? Like systemd detecting (no idea how it does it) that
> camlistored is dead because it's taking a bit of time to restart, and then
> trying to start it on its own as well?
> Maybe we should increase a bit the the RestartSec param in the service? Or
> maybe instead of restarting we do a kill when we're in the "running on gce"
> case (and let systemd restart camli)?
>
> @bradfitz <https://github.com/bradfitz> do you think it's worth
> investigating, or do you know there's no risk at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camlistore/camlistore/issues/558#issuecomment-69622958>
> .
>



-- 
سلمان

**Comment by mpl** [comment]
@saljam good to know, thanks.
