### ISSUE TITLE
Interaction awkwardness with "Pudgy" menu activation

### ISSUE THREAD

**Issue by edrex** [perkeep/perkeep#560]
When using a cursor pointing device, I generally expect to activate menus by clicking, leading to the following surprising interaction:
1. I move my cursor over the menu root
2. I click
3. (actually just before 2) the hover timeout is reached and the menu hover activates
4. my click results in the menu closing again

I pretty much do this every time i interact with the menu.

The Pudgy menu opens on hover/pointer down and closes on fade/pointer down, presumably so that it works on both cursor and touch devices.

Proposal 1: Drop the activate on hover behavior. Hover only works on non-touch devices, and thus should be shunned IMO

Proposal 2: Track whether the menu was activated by hover or by pointer down, and only close by the same mode.

**Comment by aboodman** [comment]
Sorry for some reason these notices aren't reaching my email, so I'm slow to reply. Will try to fix. Anyway...

Agree. Patches welcome.

**Comment by mpl** [comment]
fixed by 46f31ba425745584beb573d4d5c53c0ecf3916b1
