### ISSUE TITLE
android: application crashes on upload - lolipop

### ISSUE THREAD

**Issue by risico** [perkeep/perkeep#583]
Repost from: https://groups.google.com/forum/#!topic/camlistore/QMJ2gHHAd8M

I managed to get it down to:

```
2083-2311/org.camlistore D/UploadThread/stderr-child﹕ /data/data/org.camlistore/files/camput.bin[1]: syntax error: '��4�4' unexpected
```

I even compiled camput.arm to a simple hello-world like program, but it still gives the same error. At this point I am out of ideas. One thing I can think of is that I compiled camput wrongly. 

I am using Go 1.4.2. I did the whole bash.make linux/arm process.

I see now that Go can compile directly to android, maybe it's time to move to that? 

---

Edit:

Just remembered, this all started from a bug report from a Nexus 5 user in which the application crashes when it tries to upload. As stated on the Google groups report, I managed to "fix" that by setting the permissions again on the camput.bin right before upload, that's a ghetto fix I know, but it doesn't crash anymore. Now when I try to upload, I get the syntax error above.

**Comment by tgulacsi** [comment]
Just a blind shoot: I've seen such errors with camlistore behind nginx.
I've had to move to http or remove the proxy before it.

**Comment by risico** [comment]
@tgulacsi You mean when you tired to send data to the go camput(/camlistore) binary it responded with that?

I am thinking that it has something to do with the go compiler, given that the same error happens (or the scrambled text modifies a bit)  even when I simply replace the camput binary (on android) to with a simple hello world and when I access it via java's getRuntime().exec(binaryPath('camput.bin')); the command fails and I get the stdError output like the error above (or again, a bit modified).

I am going to try and compile in docker as I see that's something you guys used. Hopefully I can get closer to the problem heh.

**Comment by mpl** [comment]
Just to be sure, why is the log saying that the server is "host.com" everywhere? Did you voluntarily change that yourself for anonymity reasons (which is fine) ?

**Comment by mpl** [comment]
@risico also, how did you get/install the app? from the market? if not, and you built it yourself, what version of camput did you use as the asset?

**Comment by mpl** [comment]
@risico app from the google play store works here. Also with a fresh build with camput 2015-03-05-5c93570. On nexus 4. Are you saying that you're having problems on nexus 5 and/or on an android emulator?

**Comment by risico** [comment]
@mpl 

1. host.com, yeah, edited by me :) 
2 and 3: 

Downloaded from the store, on my Nexus 4, it works perfectly. 

The problem is on a Nexus 5 (camlistore downloaded from the store) which sadly I don't have at hand and in the emulator. I think on the Camlistore Uploader page there's a review of some Nexus 5 user experiencing the same issue.

What seems fishy for me is that, I get a similar error with just a plain Go program, compiled for linux/arm then trying to run it on the android, I get the same error. (syntax error: '��4�4'). So either I compile the Go in a bad way, or there's some higher issue here.

Can I get some precompiled binaries from somewhere else to test? I am compiling on OSX 10.10 with go version go1.4.2.

**Comment by mpl** [comment]
@risico sure, here are the apk I built yesterday, and the camput for arm it uses behind the scenes:

http://storage.googleapis.com/camlistore-tmp/CamliActivity-debug.apk
http://storage.googleapis.com/camlistore-tmp/camput.arm

However, I don't see why they'd work better than the one from the google store. But yeah, maybe at least that will tell you if you're doing something wrong when building yourself.

**Comment by risico** [comment]
Running in the emulator using your APK. 
![image](https://cloud.githubusercontent.com/assets/181740/6601433/5579825a-c81e-11e4-8972-db109cfafe4b.png)

Using my APK + your camput:
![image](https://cloud.githubusercontent.com/assets/181740/6601601/41ab883a-c81f-11e4-9100-5d76fb156a68.png)

Did you try to run it in the emulator? Different virtual devices?

**Comment by mpl** [comment]
nope. I don't think I've ever bothered setting up an android emulator. Maybe I will then...

**Comment by risico** [comment]
Hmm. I think I found it. And as per usual I think it was me. 

Apparently the emulators using x86 by default. Creating some more different emulators to test and make sure.

**Comment by risico** [comment]
Nexus 5 Android 5.1 (level 22) ARM 
![image](https://cloud.githubusercontent.com/assets/181740/6602162/abec94f2-c822-11e4-997f-3ff630f9ec8e.png)
![image](https://cloud.githubusercontent.com/assets/181740/6602266/361bab2c-c823-11e4-8a8e-2d846b117494.png)

Here it goes further, but no file uploaded and it returns to Idle. Logs don't say much.

**Nexus 5 5.0.1 (level 21) ARM** - It worked 
![image](https://cloud.githubusercontent.com/assets/181740/6602414/30b2f022-c824-11e4-96e6-edb98e98b13e.png)

Hmm. All looks good.

**Comment by mpl** [comment]
So, no more problem until you get more info from your friend?

**Comment by risico** [comment]
Ok, tested on all of them, 4, 5 (21 and 22 API levels) ARM. Works as expected. 
I guess I've to get the Nexus 5 in hand see what actually caused the crash.

Some other small bugs:
The upload animation icon sometimes it doesn't go away.
No error when the username/password is wrong.

Android development ain't fun.

**Comment by risico** [comment]
I got my friend to try again. With your debug build as well. Same result.

This one is a woozy. I am hoping someone has an actual Nexus 5 device. Asking friends around.

![image](https://cloud.githubusercontent.com/assets/181740/6678100/e175a346-cc3e-11e4-85b9-47980b295205.png)
You can see the uploader icon being stuck in the notification bar.


Will keep on poking around.

**Comment by mpl** [comment]
fwiw, at least @bradfitz also has a nexus 5, and I'm pretty sure he's tried the app on it :-)
Maybe not with lollipop yet though.

You sure you can't get your friend to give us logs? you did get him to install the apk after all...

**Comment by saljam** [comment]
I have a Nexus 5 and indeed the app had been broken for me for a while—I
just never got around to look into it... Well, because Java.

I'm not sure if it's the same issue, this is what I get: when I trigger an
upload, the progress bars don't progress, the http_start and
http_res_headers counters increases quite quickly (+2 per second, I'd say)
then after about a minute the app would say "upload process ended". Nothing
is reported on the server.

I'll double check my configuration and post the logs here later.

**Comment by risico** [comment]
@mpl

It took me some time to get him through the settings to allow apps from Unknown Sources :baby:. 

The last thing I can think of is the weird permission error I got at the beginning, although I cannot reproduce it now.

```
    --------- beginning of crash
03-03 05:04:37.523    2318-2415/org.camlistore E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-173
    Process: org.camlistore, PID: 2318
    java.lang.RuntimeException: java.io.IOException: Error running exec(). Command: [/data/data/org.camlistore/files/camput.bin, --server=http://host.com, file, -stdinargs, -vivify] Working Directory: null Environment: [ANDROID_ROOT=/system, CAMPUT_ANDROID_OUTPUT=1, LOOP_MOUNTPOINT=/mnt/obb, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, CAMLI_CACHE_DIR=/data/data/org.camlistore/cache, EXTERNAL_STORAGE=/storage/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=9, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, CAMLI_TRUSTED_CERT=, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar, ANDROID_PROPERTY_WORKSPACE=8,0, CAMLI_AUTH=userpass:user:password, ANDROID_STORAGE=/storage]
            at org.camlistore.UploadThread.run(UploadThread.java:179)
     Caused by: java.io.IOException: Error running exec(). Command: [/data/data/org.camlistore/files/camput.bin, --server=http://host.com, file, -stdinargs, -vivify] Working Directory: null Environment: [ANDROID_ROOT=/system, CAMPUT_ANDROID_OUTPUT=1, LOOP_MOUNTPOINT=/mnt/obb, LD_PRELOAD=libsigchain.so, ANDROID_BOOTLOGO=1, CAMLI_CACHE_DIR=/data/data/org.camlistore/cache, EXTERNAL_STORAGE=/storage/sdcard, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=9, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, CAMLI_TRUSTED_CERT=, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar, ANDROID_PROPERTY_WORKSPACE=8,0, CAMLI_AUTH=userpass:user:password, ANDROID_STORAGE=/storage]
            at java.lang.ProcessManager.exec(ProcessManager.java:211)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
            at org.camlistore.UploadThread.run(UploadThread.java:170)
     Caused by: java.io.IOException: Permission denied
            at java.lang.ProcessManager.exec(Native Method)
            at java.lang.ProcessManager.exec(ProcessManager.java:209)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:195)
            at org.camlistore.UploadThread.run(UploadThread.java:170)
03-03 05:04:37.536    2318-2318/org.camlistore D/UploadService﹕ in handleCommand() for onStart() intent: Intent { cmp=org.camlistore/.UploadService }
03-03 05:04:45.805    2318-2415/org.camlistore I/Process﹕ Sending signal. PID: 2318 SIG: 9
```

@saljam Does it crash for you when you try and upload or it just hangs in there, writing the "debug" info never completing the upload but no crash?

I can try some things and if you want I can send them over to you to test.

**Comment by saljam** [comment]
@risico the android app doesn't crash—it stays responsive. I'm not sure about the state of camput though.

I'm happy to try what you send, let me get the logs for this first.

**Comment by risico** [comment]
@saljam From experience (which is not that broad, I am a new user around) most of the time the issues are config wise. 

Logs are welcome. Maybe we can fix more than one issue.

**Comment by mpl** [comment]
naughty @saljam , not reporting bugs and waiting for newcomers to report them for him!

**Comment by saljam** [comment]
Heh, I wasn't really sure it's a bug! And it turns out it isn't. It works fine for me. (Turns out I had disabled the vivify password to test something on the server and forgotten to reenable it.) Sorry about the noise!

That's on a Nexus 5 (screenshot uploaded using the app, even):
![screenshot_2015-03-18-10-33-17](https://cloud.githubusercontent.com/assets/751023/6704706/6206ca8e-cd5d-11e4-8252-d9b92688171d.png)

That said, it would be nice if the app reported auth issues, rather than silently ignoring the "401 unauthorised" response from the server

**Comment by cliveb** [comment]
Related camput.arm question. I've sent up tool chain with rel 22 to rebuild the app for Android 5.1 and Camlistore 0.9. I removed .gitignore from client/android/assets and .gitignore from client/android after 'make' camlistore and andriod. I still don't see camput.arm on my Mac 10.10.3 (newbie at this). What am I doing wrong?

**Comment by mpl** [comment]
Why would you remove the .gitignore files? they are of no consequence to the building process.

from what I recall and what the Makefile says, you either:

1) (old way)
  -cross-compile camput.arm yourself and place it in assets
  -make install

or 2) docker way:
  -make env // to build the docker image with go and the android sdk installed
  -make dockerdebug

**Comment by lindner** [comment]
Is this issue still relevant?

**Comment by mpl** [comment]
nope indeed. the issue was fixed both for @risico and @saljam as far as i can see.
