### ISSUE TITLE
amazon cloud drive blobserver

### ISSUE THREAD

**Issue by marshauf** [perkeep/perkeep#759]
Hello,
I would like to use my Amazon cloud drive as a blob server.
A go client is available here https://github.com/go-acd/acd , it seems like all three required operations are supported: get, put, enumerate
I would start implementing it, if nobody is working on one.

**Comment by mpl** [comment]
Hi,

So, just to be sure, that's different from S3, isn't it?

**Comment by marshauf** [comment]
Yes, it's like Google Drive. I got it with Amazon prime and I am not using it, so I thought using it as a backup would be nice.
Website: https://www.amazon.com/clouddrive/home
The documentation: https://developer.amazon.com/public/apis/experience/cloud-drive/

**Comment by mpl** [comment]
Then sure, if you think it's an interesting target just go for it.

Also, be aware that if we want a blobpacked on top of it (which is generally a good idea for cloud storage, for efficiency reasons), we need to be able to implement SubFetch for it too.

See pkg/blobserver/google/cloudstorage/storage.go for inspiration/example.

**Comment by joshlf** [comment]
Any progress on this? I'd use it if it existed.

**Comment by marshauf** [comment]
Hello, I stopped working on it and didn't get far. I also moved on and will
not implement this feature, sorry.

**Comment by joshlf** [comment]
Ah oh well. Thanks for getting back to me so quickly!

**Comment by mpl** [comment]
OP is not interested anymore.
