### ISSUE TITLE
reclaim disk space by running `gc.Collect()`

### ISSUE THREAD

**Issue by mkorenkov** [perkeep/perkeep#792]
I suffer as I have to presort photos and videos before uploading them to camlistore. As camlistore ignores my intention to delete the stuff I don't want to keep. It's just marked as deleted, nothing is really gone.

Btw, we had to give up the idea of using camlistore as our backup system in my previous company just because we could not wipe the old data.

I remember some old discussions about garbage collection of deleted objects. I have checked the code and thought it seems, that `gc.Collect()` is implemented, I didn't find any references to it except ones in the test.

I've made a test: I have uploaded and deleted a couple of 2G videos to my local camlistore server and 1 hour later they were still there, wasting my disk space.

**Comment by mpl** [comment]
The garbage collector is not finished. I need to resurrect https://camlistore-review.googlesource.com/2340 the day we decide it's a more important matter. So yeah, therefore camlistored does not call it at all for now.
Then we'll enable it very carefully (i.e. it won't run automatically at first).

**Comment by mpl** [comment]
We know the GC needs to be finished.

**Comment by bj0** [comment]
is there an issue for tracking the status of the GC?  I keep wanting to play with perkeep but I have a feeling i'll fill up my drive.

**Comment by mpl** [comment]
@bj0 I don't think there was one, so here it is:
https://github.com/perkeep/perkeep/issues/1076

**Comment by bradfitz** [comment]
> I keep wanting to play with perkeep but I have a feeling i'll fill up my drive.

Just play with it and see. Hint: it won't. :) I've been using it for years and my disks keep getting larger faster than I acquire data. And also I never delete anything, so a GC would be kinda useless.

But if you play with it and have a different experience than me, your drive isn't wasted. You can just delete all your Perkeep data and get your space back.

**Comment by bj0** [comment]
I'll probably give it a go soon.  Can I ask, what do you primarily use it for with your experience?  How judicious are you about what you put into it (do you avoid things like VM images and files that you know are only temporary, like downloaded files)?

**Comment by bradfitz** [comment]
Yeah, I use the camput client configuration file to exclude known junk directories (like Downloads, VMs, etc).
