### ISSUE TITLE
webui: drag-and-drop of directory stalls endlessly

### ISSUE THREAD

**Issue by cyphar** [perkeep/perkeep#831]
If I try to drag-and-drop a directory to "upload" it, the upload will be stuck at "0%" endlessly. The directory has to have at least one file in it in order for this to happen. If the directory is empty then the upload treats it as though it were a file (not a directory).

This error is visible in the console (which means we also should quit the upload animation and loading bar if there is an error while uploading as well -- that's a separate issue):

```
Uncaught NotFoundError: Failed to execute 'readAsArrayBuffer' on 'FileReaderSync': A requested file or directory could not be found at the time an operation was processed.
```

**Comment by mpl** [comment]
yes, drag and drop of directories is not supported.
