### ISSUE TITLE
webui: trying to view non-images results in "not found"

### ISSUE THREAD

**Issue by cyphar** [perkeep/perkeep#834]
This also happens for directories, which is quite odd. All of this is from `master`. If you try to open any file, you get this screen:

![not found](https://cloud.githubusercontent.com/assets/2888411/17441943/d2cb449a-5b76-11e6-8934-012d49f52eb2.png)

But even if you go through the permanode screen to find the _actual_ blob (the refid shown in the screenshot is of the permanode), you still don't see any data in the "blob content". You can however get the blob contents using `camget`.

![no content](https://cloud.githubusercontent.com/assets/2888411/17441973/f8a713ec-5b76-11e6-9848-c1cd3f77f958.png)

I get the following error in the error log:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
cam.BlobDetail<.handleBlobContents_()
 blob_detail.js:160
[33]</ReactCompositeComponentMixin._bindAutoBindMethod/boundMethod()
 react-with-addons.js:6441
cam.ServerConnection.prototype.handleXhrResponseText_()
 server_connection.js:373
bound ()
 self-hosted:792
goog.events.EventTarget.prototype.fireListeners()
 eventtarget.js:288
goog.events.EventTarget.dispatchEventInternal_()
 eventtarget.js:385
goog.events.EventTarget.prototype.dispatchEvent()
 eventtarget.js:200
goog.net.XhrIo.prototype.onReadyStateChangeHelper_()
 xhrio.js:799
goog.net.XhrIo.prototype.onReadyStateChangeEntryPoint_()
 xhrio.js:745
goog.net.XhrIo.prototype.onReadyStateChange_()
 xhrio.js:729
bound ()
```

**Comment by mpl** [comment]
@cyphar we probably totally missed that issue, sorry about that. I'm going to close it, because I assume you probably have moved on since then. If not, and you still care, please do reopen it and I'll debug it with you.
