### ISSUE TITLE
Getting WAL warning for sqlite using included sqlite==v3.12.0

### ISSUE THREAD

**Issue by 0xCMP** [perkeep/perkeep#840]
There is an issue at https://github.com/camlistore/camlistore/blob/75d60962f66dd2eaad02f936fc3d4aff2c968f5b/cmd/camtool/dbinit.go#L94 because the function being used to check if WAL is supported doesn't work for versions 3.10 and above.

At this line (https://github.com/camlistore/camlistore/blob/75d60962f66dd2eaad02f936fc3d4aff2c968f5b/pkg/sorted/sqlite/dbschema.go#L79) the check done will fail because "12" isn't considered higher than "7."

**Comment by cmpis** [comment]
Don't know if this is a solved problem in go standard lib, but I coded up a quick solution to this

https://play.golang.org/p/XnJ75lrLPj

Not sure where you guy would like me to put it or if it's too complicated for this.

**Comment by mpl** [comment]
ugh, that is indeed lame, thanks for the bug report.

@cmpis If you are interested in contributing a fix, please see https://camlistore.org/code#contributing. Otherwise, please let me know and I'll fix it myself.

**Comment by cmpis** [comment]
I'm going to try to contribute something by today.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14746
