### ISSUE TITLE
Unify caching inside server, add explicit cache config

### ISSUE THREAD

**Issue by DanielHeath** [perkeep/perkeep#898]
I've been looking at ways to run camlistore on an inexpensive VPS (eg an aws t2.micro with 512mb ram). 

Most things work very well, but image / video thumbnailing loads slowly and often fails (typically I'll upload everything from my camera at once so there'll be 1gb+ of video nodes on the same page of the web UI).

I've dug around a bit in thumbcache / ThumbMeta but couldn't see a straightforward way to pregenerate thumbnails. Would a sync target that thumbnails everything sent to it be a sensible way to do this?

**Comment by DanielHeath** [comment]
After a bit of testing, this actually works quite well with a local disk blobstore (as long as you have swap), but is extremely slow when reading from s3.

**Comment by bradfitz** [comment]
I think we should probably keep the index/corpus in memory (on that 512MB) and then defer thumbnailing and as much work as possible to Lambda or other platforms' Serverless functions.

**Comment by DanielHeath** [comment]
It performed fine when thumbnailing off an ebs volume.

S3 should be quite fast; could the rate limiting for s3 uploads be getting applied to downloads as well? That might explain why thumbnailing 15mb of images takes 20+ minutes instead of 5 seconds.

Thanks,
Daniel Heath

**Comment by DanielHeath** [comment]
Digging in a bit further, I can see that whilst s3 has an internal cache, it doesn't use it for `Stat`.

It looks like most of the caching code in the s3 package could be pulled out (and this bug fixed) if we used `proxycache` to put a memory cache in front of s3 (instead of hard-coding an s3-specific memory cache). 

This would simplify the code and - I suspect - improve performance markedly.

**Comment by DanielHeath** [comment]
Alright, https://camlistore-review.googlesource.com/c/camlistore/+/15846 should fix this - vastly faster on my EC2 instance.

**Comment by DanielHeath** [comment]
For now, I've hard-coded my personal instance to use 500mb of ram for the cache - ideally I'd like it to persist across restarts, but they don't happen often.

**Comment by DanielHeath** [comment]
Would you consider support for a filesystem-backed LRU cache (updating atime or something, where supported)? 

That would make it easy to support "put most of my stuff on cheap, slow storage but mirror the most recently used N gb to my SSD".

**Comment by bradfitz** [comment]
@DanielHeath, thanks for looking at this.

I think our current caching inside the server needs to be unified. Ad-hoc caches like the one inside the S3 implementation you touched in https://camlistore-review.googlesource.com/c/camlistore/+/15846 ideally shouldn't even exist.

My current plan is to finish the config changes (#1134) and then add support in the config file for a `[cache]` section and let you specify both memory and disk sizes, and then modify the server such that all activity goes via the cache (UI, thumbnailing, all HTTP handlers, etc) and then remove things like the S3 cache.

Also, the `proxycache` type has some current limitations: it doesn't initialize its LRU on start-up, so on shutdown, it strands blobs in its cache that never get cleaned up.

We probably want one that persists an LRU on disk (as you mentioned). We could add some smarts to the `files`/`localdisk` type to use a lazy modtime (only touch the modtime if it's older than, say, N days), or we could store the LRU in a `sorted.KeyValue`, and slurp that `proxycache` start-up, regardless of the backing `blobserver.Storage` implementation. But I think that's overkill to start. I think using modtimes in `localdisk` is fine to start, and then just enumerating all files on start-up to learn the modtimes to populate the LRU.
