### ISSUE TITLE
Authentication with Amazon S3 fails due to new auth mechanism

### ISSUE THREAD

**Issue by oec** [perkeep/perkeep#911]
I get a panic on startup of camlistore, with this final information:

"s3": Error listing bucket XXXXXXXX s3.ListBucket: status 400: <?xml version=
"1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provid
ed is not supported. Please use AWS4-HMAC-SHA256.</Message>...</Error>

**Comment by mpl** [comment]
thanks, I'll look into it.

**Comment by mpl** [comment]
@oec hey. Could it be that the access credentials you're using are not accepted anymore by S3 for security reasons (too old)?

Could you please verify by running the s3 unit tests:

go test ./pkg/blobserver/s3/ -s3_key access_key -s3_secret secret_key -s3_bucket some_test_bucket -testdata /some/dir/with/data

I've just run the tests with a freshly generated key and there was no problem for me.

**Comment by oec** [comment]
@mpl I just tried the test-case, same issue - status 400 with message:

`<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>`

The credentials are pretty new (two days old).  Maybe different s3-regions have different requirements on the authentication?

**Comment by oec** [comment]
Aha, here is a clue (from the [AWS documentation](http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html), highlights are mine):

> **Supported Regions and Services**
> 
> The following regions don't support Signature Version 2. **You must use Signature Version 4 to sign API requests in these regions**:
> 
> US East (Ohio) Region
> Canada (Central) Region
> Asia Pacific (Mumbai) Region
> Asia Pacific (Seoul) Region
> **EU (Frankfurt) Region**
> EU (London) Region
> China (Beijing) Region

**Comment by oec** [comment]
If I understand correctly, Version 4 of the authentication method would work in any region (for the S3 API, at least)

**Comment by mpl** [comment]
ah, I see, thanks for looking into it.

Let me know if you want to write a CL for it, but otherwise I'll get to it soon.

**Comment by oec** [comment]
I could work on it over the weekend, simply lifting the implementation to version 4 of then authentication.

**Comment by oec** [comment]
No hurry.  I like to give it a shot, stay tuned.

**Comment by AstromechZA** [comment]
Was there any more progress on this issue? Hit the same thing now with a bucket in Frankfurt..

**Comment by oec** [comment]
I've had spent an evening implementing the Signature Version 4 for camlistore/perkeep a couple of months ago to the point where I believe to I had the authentication implemented correctly (I didn't  get any error messages from AWS anymore), but alas, it didn't work:  I was able to put data into camlistore, without any error messages, but the data didn't show up in the bucket. That's where I left and did not have had the time to debug it any further.

**Comment by oec** [comment]
You'll find my version of camlistore/pkg/misc/amazon/s3/auth.go here:
https://gist.github.com/oec/b84ad369c50ec5c59008b466e232bfa6
Keep in mind that my code is from August 17 2017, it might not compile with the current version of perkeep.

But I'd suggest to start fresh but using either
- https://github.com/smartystreets/go-aws-auth  or
- https://github.com/aws/aws-sdk-go/

**Comment by L42y** [comment]
Using Signature Version 4 can enable people to use AWS China's regions, including Beijing & Ningxia, also need to support specifying AWS China's special endpoint `s3.cn-north-1.amazonaws.com.cn` in order to achieve that, relevant information: http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region

**Comment by oec** [comment]
Good news: I have managed to debug my own code and fixed the blocking issues!  Now I have perkeep running properly using a s3-bucket in the eu-central-1 region with v4 signature.  I'll prepare a pull request for it until Thursday.

**Comment by oec** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17066

**Comment by euank** [comment]
Alternately, https://perkeep-review.googlesource.com/c/perkeep/+/17226 will also fix this.

@L42y: it should be possible to get that cl to work with AWS China, but it will unfortunately require writing a lowlevel config to set the "aws_region" value to 'cn-north-1' (which will automatically use the write endpoint since it uses the aws sdk).

**Comment by L42y** [comment]
@euank can't wait to see this get merged, great work!

**Comment by L42y** [comment]
@euank after pulling the master version and convert to low-level config, I can use the AWS China regions, you are my hero!
