### ISSUE TITLE
http basic auth credentials lost after clicking the Map tab

### ISSUE THREAD

**Issue by khimaros** [perkeep/perkeep#966]
The user interface works fine with HTTP basic auth (behind nginx), but clicking the Map causes Chrome to prompt for credentials in a loop. I haven't yet identified the root cause. Let me know if there's additional information I can provide to help troubleshoot.

**Comment by mpl** [comment]
I've just tried with my usual front-end setup and I can't reproduce.

So yes, as usual, please provide the server-config.json, and the relevant details about the proxy (https or not, ports, etc).

btw, as like most of the UI, the map component does not actually use HTTP basic auth, even though it first relies on it for "bootstrapping".

**Comment by khimaros** [comment]
Duplicate of https://github.com/perkeep/perkeep/issues/1221
