### ISSUE TITLE
android: uploading to a let's encrypt instance still requires to treat it as a self-signed

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#974]
The android app seems to be failing to upload to a Camlistore instance that uses a Let's Encrypt certificate, unless the certificate is treated a self-signed, i.e. requiring the user to enter the prefix of the certificate's sha256 in the app (which is a pain).

I thought I had already looked into that and fixed it, but apparently not.

**Comment by mpl** [comment]
@tdilo if you're interested in looking into that, it would be much appreciated :-)

**Comment by tdilo** [comment]
Will do :)

**Comment by bradfitz** [comment]
This is bizarre.

Any theories why?

**Comment by mpl** [comment]
I wanted to refresh my memory on that but I supposed it had something to do with the fact that afair, we hardcode a pool of root certs in the android client, and that maybe we're missing the ones related to Let's Encrypt?

**Comment by tdilo** [comment]
On android, the system root certs should be parsed and used. The hardcoded pool may be used on some systems where this fails (didn't check too closely), but at least on my device `/system/etc/security/cacerts` exists and is not empty.

With this change, my Let's Encrypt certificate works well and a certificate with mismatching server name is rejected properly:
https://camlistore-review.googlesource.com/c/camlistore/+/14846
