### ISSUE TITLE
Create a Perkeep package for Synology NAS

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#986]
Synology NASes are popular and have a nice package app store thing.
 
Let's package Perkeep.

See https://developer.synology.com/developer-guide/getting_started/index.html

/cc @lindner @mpl

**Comment by edrex** [comment]
I'm about to jump on the Synology bandwagon

**Comment by bradfitz** [comment]
@edrex, does that mean you're about to buy a Synology NAS or you're going to package Perkeep? :)

**Comment by edrex** [comment]
Buying a Synology right after Christmas. [I already committed](https://groups.google.com/d/msg/sandstorm-dev/pMhXs0nvVRI/UfrVvBJ9DgAJ) to packaging Sandstorm for Synology, which is a bigger deal because sandboxes, so I can do Camlistore too.

**Comment by edrex** [comment]
Cross compiling for all the weird CPUs various Synology boxes contain seems like it could be a pain. Hopefully they have some automation to make it easier. I haven't looked into it. My box with be amd64.

**Comment by bradfitz** [comment]
> Cross compiling for all the weird CPUs various Synology boxes contain seems like it could be a pain. 

Well, the main Go compiler will do x86 and ARM cross-compilation trivially. The ppc (which I assume is 32-bit) isn't possible with the main Go compiler, though. We'd need to use gccgo there. Or could we ignore those two 2013 models? (DS213+, DS413)

**Comment by bpollack** [comment]
It's worth noting that Synology now supports Docker pretty cleanly, so publishing images and instructions for generic Docker setups could cover this without necessarily having a custom Synology package. I've been poking at that direction a bit this week.

**Comment by bradfitz** [comment]
> It's worth noting that Synology now supports Docker pretty cleanly, so publishing images and instructions for generic Docker setups could cover this without necessarily having a custom Synology package. I've been poking at that direction a bit this week.

@bpollack, keep us updated!

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/17546
