### ISSUE TITLE
Apply to Google Summer of Code

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#992]
We should apply to the Google Summer of Code:

https://developers.google.com/open-source/gsoc/

> Organizations apply starting January 4th, 2018.

/cc @mpl @willnorris @lindner

**Comment by mpl** [comment]
Does it not imply a significant amount of mentoring?

**Comment by willnorris** [comment]
Relevant reading:  https://google.github.io/gsocguides/mentor/, specifically the "Org Admin" section in the sidebar.  Mathieu is certainly right that this involves a significant amount of time on the part of the mentors.  If it's something we're going to do, we need to be putting an [ideas list](https://google.github.io/gsocguides/mentor/making-your-ideas-page) together... well, some time ago.

**Comment by lindner** [comment]
I think we missed the cutoff for this.

**Comment by bradfitz** [comment]
Yeah, sorry. Next year, I guess.

**Comment by mpl** [comment]
let's open another bug next year then.
